// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	"github.com/piratecash/corsa/internal/core/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrafficSource creates a new instance of MockTrafficSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrafficSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrafficSource {
	mock := &MockTrafficSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrafficSource is an autogenerated mock type for the TrafficSource type
type MockTrafficSource struct {
	mock.Mock
}

type MockTrafficSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrafficSource) EXPECT() *MockTrafficSource_Expecter {
	return &MockTrafficSource_Expecter{mock: &_m.Mock}
}

// HandleLocalFrame provides a mock function for the type MockTrafficSource
func (_mock *MockTrafficSource) HandleLocalFrame(frame protocol.Frame) protocol.Frame {
	ret := _mock.Called(frame)

	if len(ret) == 0 {
		panic("no return value specified for HandleLocalFrame")
	}

	var r0 protocol.Frame
	if returnFunc, ok := ret.Get(0).(func(protocol.Frame) protocol.Frame); ok {
		r0 = returnFunc(frame)
	} else {
		r0 = ret.Get(0).(protocol.Frame)
	}
	return r0
}

// MockTrafficSource_HandleLocalFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLocalFrame'
type MockTrafficSource_HandleLocalFrame_Call struct {
	*mock.Call
}

// HandleLocalFrame is a helper method to define mock.On call
//   - frame protocol.Frame
func (_e *MockTrafficSource_Expecter) HandleLocalFrame(frame interface{}) *MockTrafficSource_HandleLocalFrame_Call {
	return &MockTrafficSource_HandleLocalFrame_Call{Call: _e.mock.On("HandleLocalFrame", frame)}
}

func (_c *MockTrafficSource_HandleLocalFrame_Call) Run(run func(frame protocol.Frame)) *MockTrafficSource_HandleLocalFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 protocol.Frame
		if args[0] != nil {
			arg0 = args[0].(protocol.Frame)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrafficSource_HandleLocalFrame_Call) Return(frame1 protocol.Frame) *MockTrafficSource_HandleLocalFrame_Call {
	_c.Call.Return(frame1)
	return _c
}

func (_c *MockTrafficSource_HandleLocalFrame_Call) RunAndReturn(run func(frame protocol.Frame) protocol.Frame) *MockTrafficSource_HandleLocalFrame_Call {
	_c.Call.Return(run)
	return _c
}
