// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package capture

import (
	"net/netip"

	"github.com/piratecash/corsa/internal/core/capture"
	"github.com/piratecash/corsa/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnResolver creates a new instance of MockConnResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnResolver {
	mock := &MockConnResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnResolver is an autogenerated mock type for the ConnResolver type
type MockConnResolver struct {
	mock.Mock
}

type MockConnResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnResolver) EXPECT() *MockConnResolver_Expecter {
	return &MockConnResolver_Expecter{mock: &_m.Mock}
}

// AllConnInfo provides a mock function for the type MockConnResolver
func (_mock *MockConnResolver) AllConnInfo() []capture.ConnInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllConnInfo")
	}

	var r0 []capture.ConnInfo
	if returnFunc, ok := ret.Get(0).(func() []capture.ConnInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]capture.ConnInfo)
		}
	}
	return r0
}

// MockConnResolver_AllConnInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllConnInfo'
type MockConnResolver_AllConnInfo_Call struct {
	*mock.Call
}

// AllConnInfo is a helper method to define mock.On call
func (_e *MockConnResolver_Expecter) AllConnInfo() *MockConnResolver_AllConnInfo_Call {
	return &MockConnResolver_AllConnInfo_Call{Call: _e.mock.On("AllConnInfo")}
}

func (_c *MockConnResolver_AllConnInfo_Call) Run(run func()) *MockConnResolver_AllConnInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnResolver_AllConnInfo_Call) Return(connInfos []capture.ConnInfo) *MockConnResolver_AllConnInfo_Call {
	_c.Call.Return(connInfos)
	return _c
}

func (_c *MockConnResolver_AllConnInfo_Call) RunAndReturn(run func() []capture.ConnInfo) *MockConnResolver_AllConnInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ConnInfoByID provides a mock function for the type MockConnResolver
func (_mock *MockConnResolver) ConnInfoByID(id domain.ConnID) (capture.ConnInfo, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ConnInfoByID")
	}

	var r0 capture.ConnInfo
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(domain.ConnID) (capture.ConnInfo, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ConnID) capture.ConnInfo); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(capture.ConnInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ConnID) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockConnResolver_ConnInfoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnInfoByID'
type MockConnResolver_ConnInfoByID_Call struct {
	*mock.Call
}

// ConnInfoByID is a helper method to define mock.On call
//   - id domain.ConnID
func (_e *MockConnResolver_Expecter) ConnInfoByID(id interface{}) *MockConnResolver_ConnInfoByID_Call {
	return &MockConnResolver_ConnInfoByID_Call{Call: _e.mock.On("ConnInfoByID", id)}
}

func (_c *MockConnResolver_ConnInfoByID_Call) Run(run func(id domain.ConnID)) *MockConnResolver_ConnInfoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ConnID
		if args[0] != nil {
			arg0 = args[0].(domain.ConnID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnResolver_ConnInfoByID_Call) Return(connInfo capture.ConnInfo, b bool) *MockConnResolver_ConnInfoByID_Call {
	_c.Call.Return(connInfo, b)
	return _c
}

func (_c *MockConnResolver_ConnInfoByID_Call) RunAndReturn(run func(id domain.ConnID) (capture.ConnInfo, bool)) *MockConnResolver_ConnInfoByID_Call {
	_c.Call.Return(run)
	return _c
}

// ConnInfoByIP provides a mock function for the type MockConnResolver
func (_mock *MockConnResolver) ConnInfoByIP(ip netip.Addr) []capture.ConnInfo {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for ConnInfoByIP")
	}

	var r0 []capture.ConnInfo
	if returnFunc, ok := ret.Get(0).(func(netip.Addr) []capture.ConnInfo); ok {
		r0 = returnFunc(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]capture.ConnInfo)
		}
	}
	return r0
}

// MockConnResolver_ConnInfoByIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnInfoByIP'
type MockConnResolver_ConnInfoByIP_Call struct {
	*mock.Call
}

// ConnInfoByIP is a helper method to define mock.On call
//   - ip netip.Addr
func (_e *MockConnResolver_Expecter) ConnInfoByIP(ip interface{}) *MockConnResolver_ConnInfoByIP_Call {
	return &MockConnResolver_ConnInfoByIP_Call{Call: _e.mock.On("ConnInfoByIP", ip)}
}

func (_c *MockConnResolver_ConnInfoByIP_Call) Run(run func(ip netip.Addr)) *MockConnResolver_ConnInfoByIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 netip.Addr
		if args[0] != nil {
			arg0 = args[0].(netip.Addr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnResolver_ConnInfoByIP_Call) Return(connInfos []capture.ConnInfo) *MockConnResolver_ConnInfoByIP_Call {
	_c.Call.Return(connInfos)
	return _c
}

func (_c *MockConnResolver_ConnInfoByIP_Call) RunAndReturn(run func(ip netip.Addr) []capture.ConnInfo) *MockConnResolver_ConnInfoByIP_Call {
	_c.Call.Return(run)
	return _c
}
