#!/usr/bin/env python3

import argparse
import ipaddress
import json
import socket
import sys
import urllib.error
import urllib.request
from pathlib import Path


DEFAULT_RPC_URL = "http://127.0.0.1:46464"
DEFAULT_OUTPUT = "internal/core/config/chainparamsseeds.go"
DEFAULT_ARRAY_NAME = "chainParamSeedsMain"
DEFAULT_LIMIT = 16


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch peer health from RPC and generate a Bitcoin-style "
            "fixed-seed Go source file."
        )
    )
    parser.add_argument(
        "--rpc-url",
        default=DEFAULT_RPC_URL,
        help=f"RPC base URL (default: {DEFAULT_RPC_URL})",
    )
    parser.add_argument("--rpc-user", required=True, help="RPC basic auth username")
    parser.add_argument("--rpc-password", required=True, help="RPC basic auth password")
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--array-name",
        default=DEFAULT_ARRAY_NAME,
        help=f"Generated array name (default: {DEFAULT_ARRAY_NAME})",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=DEFAULT_LIMIT,
        help=f"Maximum number of peers to emit (default: {DEFAULT_LIMIT})",
    )
    return parser.parse_args()


def parse_host_port(value: str):
    value = value.strip()
    if not value:
        return None
    if value.startswith("["):
        end = value.find("]")
        if end == -1 or end + 1 >= len(value) or value[end + 1] != ":":
            return None
        return value[1:end], value[end + 2 :]
    if value.count(":") == 1:
        return value.rsplit(":", 1)
    return None


def resolve_ip(host: str):
    try:
        return ipaddress.ip_address(host)
    except ValueError:
        try:
            infos = socket.getaddrinfo(host, None, proto=socket.IPPROTO_TCP)
        except socket.gaierror:
            return None
        for family, _, _, _, sockaddr in infos:
            if family == socket.AF_INET:
                return ipaddress.ip_address(sockaddr[0])
            if family == socket.AF_INET6:
                return ipaddress.ip_address(sockaddr[0])
    return None


def is_public(ip) -> bool:
    return not (
        ip.is_private
        or ip.is_loopback
        or ip.is_link_local
        or ip.is_multicast
        or ip.is_unspecified
        or ip.is_reserved
    )


def fetch_peer_health(rpc_url: str, rpc_user: str, rpc_password: str):
    url = rpc_url.rstrip("/") + "/rpc/v1/network/health"
    request = urllib.request.Request(
        url,
        data=b"{}",
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    password_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()
    password_mgr.add_password(None, url, rpc_user, rpc_password)
    auth_handler = urllib.request.HTTPBasicAuthHandler(password_mgr)
    opener = urllib.request.build_opener(auth_handler)
    try:
        with opener.open(request) as response:
            return json.load(response)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace").strip()
        raise SystemExit(f"RPC request failed: HTTP {exc.code} {detail}") from exc
    except urllib.error.URLError as exc:
        raise SystemExit(f"RPC request failed: {exc.reason}") from exc


def select_peers(payload: dict, limit: int):
    items = payload.get("peer_health") or payload.get("peers") or []
    selected = []
    seen = set()

    for item in items:
        if not isinstance(item, dict):
            continue
        if not item.get("connected", False):
            continue
        address = str(item.get("address", "")).strip()
        parsed = parse_host_port(address)
        if parsed is None:
            continue
        host, port_text = parsed
        try:
            port = int(port_text)
        except ValueError:
            continue
        if port <= 0 or port > 65535:
            continue
        ip = resolve_ip(host)
        if ip is None or not is_public(ip):
            continue
        key = (ip.packed, port)
        if key in seen:
            continue
        seen.add(key)
        if isinstance(ip, ipaddress.IPv6Address):
            selected.append(f"[{ip.compressed}]:{port}")
        else:
            selected.append(f"{ip.compressed}:{port}")
        if len(selected) >= limit:
            break

    return selected


def render_go(array_name: str, selected) -> str:
    lines = [
        "package config\n\n",
        "/*\n",
        "List of fixed seed nodes for the corsa network.\n",
        "AUTOGENERATED by scripts/generate-seeds.py.\n",
        "\n",
        "Each line contains a bootstrap peer address in host:port form.\n",
        "*/\n",
        f"var {array_name} = []string{{\n",
    ]
    for address in selected:
        lines.append(f'\t"{address}",\n')
    lines.append("}\n")
    return "".join(lines)


def main() -> int:
    args = parse_args()
    if args.limit <= 0:
        raise SystemExit("--limit must be greater than zero")

    payload = fetch_peer_health(args.rpc_url, args.rpc_user, args.rpc_password)
    selected = select_peers(payload, args.limit)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_go(args.array_name, selected), encoding="utf-8")

    print(f"generated {output_path}")
    print(f"selected {len(selected)} peer(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
