// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCaptureProvider creates a new instance of MockCaptureProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaptureProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaptureProvider {
	mock := &MockCaptureProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCaptureProvider is an autogenerated mock type for the CaptureProvider type
type MockCaptureProvider struct {
	mock.Mock
}

type MockCaptureProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaptureProvider) EXPECT() *MockCaptureProvider_Expecter {
	return &MockCaptureProvider_Expecter{mock: &_m.Mock}
}

// StartCaptureAll provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StartCaptureAll(format string) (json.RawMessage, error) {
	ret := _mock.Called(format)

	if len(ret) == 0 {
		panic("no return value specified for StartCaptureAll")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (json.RawMessage, error)); ok {
		return returnFunc(format)
	}
	if returnFunc, ok := ret.Get(0).(func(string) json.RawMessage); ok {
		r0 = returnFunc(format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StartCaptureAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCaptureAll'
type MockCaptureProvider_StartCaptureAll_Call struct {
	*mock.Call
}

// StartCaptureAll is a helper method to define mock.On call
//   - format string
func (_e *MockCaptureProvider_Expecter) StartCaptureAll(format interface{}) *MockCaptureProvider_StartCaptureAll_Call {
	return &MockCaptureProvider_StartCaptureAll_Call{Call: _e.mock.On("StartCaptureAll", format)}
}

func (_c *MockCaptureProvider_StartCaptureAll_Call) Run(run func(format string)) *MockCaptureProvider_StartCaptureAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaptureProvider_StartCaptureAll_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StartCaptureAll_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StartCaptureAll_Call) RunAndReturn(run func(format string) (json.RawMessage, error)) *MockCaptureProvider_StartCaptureAll_Call {
	_c.Call.Return(run)
	return _c
}

// StartCaptureByConnIDs provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StartCaptureByConnIDs(connIDs []uint64, format string) (json.RawMessage, error) {
	ret := _mock.Called(connIDs, format)

	if len(ret) == 0 {
		panic("no return value specified for StartCaptureByConnIDs")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]uint64, string) (json.RawMessage, error)); ok {
		return returnFunc(connIDs, format)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64, string) json.RawMessage); ok {
		r0 = returnFunc(connIDs, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64, string) error); ok {
		r1 = returnFunc(connIDs, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StartCaptureByConnIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCaptureByConnIDs'
type MockCaptureProvider_StartCaptureByConnIDs_Call struct {
	*mock.Call
}

// StartCaptureByConnIDs is a helper method to define mock.On call
//   - connIDs []uint64
//   - format string
func (_e *MockCaptureProvider_Expecter) StartCaptureByConnIDs(connIDs interface{}, format interface{}) *MockCaptureProvider_StartCaptureByConnIDs_Call {
	return &MockCaptureProvider_StartCaptureByConnIDs_Call{Call: _e.mock.On("StartCaptureByConnIDs", connIDs, format)}
}

func (_c *MockCaptureProvider_StartCaptureByConnIDs_Call) Run(run func(connIDs []uint64, format string)) *MockCaptureProvider_StartCaptureByConnIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaptureProvider_StartCaptureByConnIDs_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StartCaptureByConnIDs_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StartCaptureByConnIDs_Call) RunAndReturn(run func(connIDs []uint64, format string) (json.RawMessage, error)) *MockCaptureProvider_StartCaptureByConnIDs_Call {
	_c.Call.Return(run)
	return _c
}

// StartCaptureByIPs provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StartCaptureByIPs(ips []string, format string) (json.RawMessage, error) {
	ret := _mock.Called(ips, format)

	if len(ret) == 0 {
		panic("no return value specified for StartCaptureByIPs")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, string) (json.RawMessage, error)); ok {
		return returnFunc(ips, format)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, string) json.RawMessage); ok {
		r0 = returnFunc(ips, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = returnFunc(ips, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StartCaptureByIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCaptureByIPs'
type MockCaptureProvider_StartCaptureByIPs_Call struct {
	*mock.Call
}

// StartCaptureByIPs is a helper method to define mock.On call
//   - ips []string
//   - format string
func (_e *MockCaptureProvider_Expecter) StartCaptureByIPs(ips interface{}, format interface{}) *MockCaptureProvider_StartCaptureByIPs_Call {
	return &MockCaptureProvider_StartCaptureByIPs_Call{Call: _e.mock.On("StartCaptureByIPs", ips, format)}
}

func (_c *MockCaptureProvider_StartCaptureByIPs_Call) Run(run func(ips []string, format string)) *MockCaptureProvider_StartCaptureByIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaptureProvider_StartCaptureByIPs_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StartCaptureByIPs_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StartCaptureByIPs_Call) RunAndReturn(run func(ips []string, format string) (json.RawMessage, error)) *MockCaptureProvider_StartCaptureByIPs_Call {
	_c.Call.Return(run)
	return _c
}

// StopCaptureAll provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StopCaptureAll() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopCaptureAll")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StopCaptureAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCaptureAll'
type MockCaptureProvider_StopCaptureAll_Call struct {
	*mock.Call
}

// StopCaptureAll is a helper method to define mock.On call
func (_e *MockCaptureProvider_Expecter) StopCaptureAll() *MockCaptureProvider_StopCaptureAll_Call {
	return &MockCaptureProvider_StopCaptureAll_Call{Call: _e.mock.On("StopCaptureAll")}
}

func (_c *MockCaptureProvider_StopCaptureAll_Call) Run(run func()) *MockCaptureProvider_StopCaptureAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaptureProvider_StopCaptureAll_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StopCaptureAll_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StopCaptureAll_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockCaptureProvider_StopCaptureAll_Call {
	_c.Call.Return(run)
	return _c
}

// StopCaptureByConnIDs provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StopCaptureByConnIDs(connIDs []uint64) (json.RawMessage, error) {
	ret := _mock.Called(connIDs)

	if len(ret) == 0 {
		panic("no return value specified for StopCaptureByConnIDs")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]uint64) (json.RawMessage, error)); ok {
		return returnFunc(connIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) json.RawMessage); ok {
		r0 = returnFunc(connIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) error); ok {
		r1 = returnFunc(connIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StopCaptureByConnIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCaptureByConnIDs'
type MockCaptureProvider_StopCaptureByConnIDs_Call struct {
	*mock.Call
}

// StopCaptureByConnIDs is a helper method to define mock.On call
//   - connIDs []uint64
func (_e *MockCaptureProvider_Expecter) StopCaptureByConnIDs(connIDs interface{}) *MockCaptureProvider_StopCaptureByConnIDs_Call {
	return &MockCaptureProvider_StopCaptureByConnIDs_Call{Call: _e.mock.On("StopCaptureByConnIDs", connIDs)}
}

func (_c *MockCaptureProvider_StopCaptureByConnIDs_Call) Run(run func(connIDs []uint64)) *MockCaptureProvider_StopCaptureByConnIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaptureProvider_StopCaptureByConnIDs_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StopCaptureByConnIDs_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StopCaptureByConnIDs_Call) RunAndReturn(run func(connIDs []uint64) (json.RawMessage, error)) *MockCaptureProvider_StopCaptureByConnIDs_Call {
	_c.Call.Return(run)
	return _c
}

// StopCaptureByIPs provides a mock function for the type MockCaptureProvider
func (_mock *MockCaptureProvider) StopCaptureByIPs(ips []string) (json.RawMessage, error) {
	ret := _mock.Called(ips)

	if len(ret) == 0 {
		panic("no return value specified for StopCaptureByIPs")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (json.RawMessage, error)); ok {
		return returnFunc(ips)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) json.RawMessage); ok {
		r0 = returnFunc(ips)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(ips)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaptureProvider_StopCaptureByIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCaptureByIPs'
type MockCaptureProvider_StopCaptureByIPs_Call struct {
	*mock.Call
}

// StopCaptureByIPs is a helper method to define mock.On call
//   - ips []string
func (_e *MockCaptureProvider_Expecter) StopCaptureByIPs(ips interface{}) *MockCaptureProvider_StopCaptureByIPs_Call {
	return &MockCaptureProvider_StopCaptureByIPs_Call{Call: _e.mock.On("StopCaptureByIPs", ips)}
}

func (_c *MockCaptureProvider_StopCaptureByIPs_Call) Run(run func(ips []string)) *MockCaptureProvider_StopCaptureByIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaptureProvider_StopCaptureByIPs_Call) Return(rawMessage json.RawMessage, err error) *MockCaptureProvider_StopCaptureByIPs_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCaptureProvider_StopCaptureByIPs_Call) RunAndReturn(run func(ips []string) (json.RawMessage, error)) *MockCaptureProvider_StopCaptureByIPs_Call {
	_c.Call.Return(run)
	return _c
}
