// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatlogProvider creates a new instance of MockChatlogProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatlogProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatlogProvider {
	mock := &MockChatlogProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatlogProvider is an autogenerated mock type for the ChatlogProvider type
type MockChatlogProvider struct {
	mock.Mock
}

type MockChatlogProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatlogProvider) EXPECT() *MockChatlogProvider_Expecter {
	return &MockChatlogProvider_Expecter{mock: &_m.Mock}
}

// FetchChatlog provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchChatlog(ctx context.Context, topic string, peerAddress string) (string, error) {
	ret := _mock.Called(ctx, topic, peerAddress)

	if len(ret) == 0 {
		panic("no return value specified for FetchChatlog")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, topic, peerAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, topic, peerAddress)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, topic, peerAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchChatlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChatlog'
type MockChatlogProvider_FetchChatlog_Call struct {
	*mock.Call
}

// FetchChatlog is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - peerAddress string
func (_e *MockChatlogProvider_Expecter) FetchChatlog(ctx interface{}, topic interface{}, peerAddress interface{}) *MockChatlogProvider_FetchChatlog_Call {
	return &MockChatlogProvider_FetchChatlog_Call{Call: _e.mock.On("FetchChatlog", ctx, topic, peerAddress)}
}

func (_c *MockChatlogProvider_FetchChatlog_Call) Run(run func(ctx context.Context, topic string, peerAddress string)) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_FetchChatlog_Call) Return(s string, err error) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchChatlog_Call) RunAndReturn(run func(ctx context.Context, topic string, peerAddress string) (string, error)) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Return(run)
	return _c
}

// FetchChatlogPreviews provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchChatlogPreviews(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchChatlogPreviews")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchChatlogPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChatlogPreviews'
type MockChatlogProvider_FetchChatlogPreviews_Call struct {
	*mock.Call
}

// FetchChatlogPreviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatlogProvider_Expecter) FetchChatlogPreviews(ctx interface{}) *MockChatlogProvider_FetchChatlogPreviews_Call {
	return &MockChatlogProvider_FetchChatlogPreviews_Call{Call: _e.mock.On("FetchChatlogPreviews", ctx)}
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) Run(run func(ctx context.Context)) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) Return(s string, err error) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// FetchConversations provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchConversations(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchConversations")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchConversations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchConversations'
type MockChatlogProvider_FetchConversations_Call struct {
	*mock.Call
}

// FetchConversations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatlogProvider_Expecter) FetchConversations(ctx interface{}) *MockChatlogProvider_FetchConversations_Call {
	return &MockChatlogProvider_FetchConversations_Call{Call: _e.mock.On("FetchConversations", ctx)}
}

func (_c *MockChatlogProvider_FetchConversations_Call) Run(run func(ctx context.Context)) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_FetchConversations_Call) Return(s string, err error) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchConversations_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Return(run)
	return _c
}

// LookupEntryInConversation provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) LookupEntryInConversation(ctx context.Context, peerAddress string, messageID string) (bool, error) {
	ret := _mock.Called(ctx, peerAddress, messageID)

	if len(ret) == 0 {
		panic("no return value specified for LookupEntryInConversation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, peerAddress, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, peerAddress, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, peerAddress, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_LookupEntryInConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupEntryInConversation'
type MockChatlogProvider_LookupEntryInConversation_Call struct {
	*mock.Call
}

// LookupEntryInConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - peerAddress string
//   - messageID string
func (_e *MockChatlogProvider_Expecter) LookupEntryInConversation(ctx interface{}, peerAddress interface{}, messageID interface{}) *MockChatlogProvider_LookupEntryInConversation_Call {
	return &MockChatlogProvider_LookupEntryInConversation_Call{Call: _e.mock.On("LookupEntryInConversation", ctx, peerAddress, messageID)}
}

func (_c *MockChatlogProvider_LookupEntryInConversation_Call) Run(run func(ctx context.Context, peerAddress string, messageID string)) *MockChatlogProvider_LookupEntryInConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_LookupEntryInConversation_Call) Return(b bool, err error) *MockChatlogProvider_LookupEntryInConversation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChatlogProvider_LookupEntryInConversation_Call) RunAndReturn(run func(ctx context.Context, peerAddress string, messageID string) (bool, error)) *MockChatlogProvider_LookupEntryInConversation_Call {
	_c.Call.Return(run)
	return _c
}
