// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatlogProvider creates a new instance of MockChatlogProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatlogProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatlogProvider {
	mock := &MockChatlogProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatlogProvider is an autogenerated mock type for the ChatlogProvider type
type MockChatlogProvider struct {
	mock.Mock
}

type MockChatlogProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatlogProvider) EXPECT() *MockChatlogProvider_Expecter {
	return &MockChatlogProvider_Expecter{mock: &_m.Mock}
}

// FetchChatlog provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchChatlog(topic string, peerAddress string) (string, error) {
	ret := _mock.Called(topic, peerAddress)

	if len(ret) == 0 {
		panic("no return value specified for FetchChatlog")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(topic, peerAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(topic, peerAddress)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(topic, peerAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchChatlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChatlog'
type MockChatlogProvider_FetchChatlog_Call struct {
	*mock.Call
}

// FetchChatlog is a helper method to define mock.On call
//   - topic string
//   - peerAddress string
func (_e *MockChatlogProvider_Expecter) FetchChatlog(topic interface{}, peerAddress interface{}) *MockChatlogProvider_FetchChatlog_Call {
	return &MockChatlogProvider_FetchChatlog_Call{Call: _e.mock.On("FetchChatlog", topic, peerAddress)}
}

func (_c *MockChatlogProvider_FetchChatlog_Call) Run(run func(topic string, peerAddress string)) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_FetchChatlog_Call) Return(s string, err error) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchChatlog_Call) RunAndReturn(run func(topic string, peerAddress string) (string, error)) *MockChatlogProvider_FetchChatlog_Call {
	_c.Call.Return(run)
	return _c
}

// FetchChatlogPreviews provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchChatlogPreviews() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchChatlogPreviews")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchChatlogPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChatlogPreviews'
type MockChatlogProvider_FetchChatlogPreviews_Call struct {
	*mock.Call
}

// FetchChatlogPreviews is a helper method to define mock.On call
func (_e *MockChatlogProvider_Expecter) FetchChatlogPreviews() *MockChatlogProvider_FetchChatlogPreviews_Call {
	return &MockChatlogProvider_FetchChatlogPreviews_Call{Call: _e.mock.On("FetchChatlogPreviews")}
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) Run(run func()) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) Return(s string, err error) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchChatlogPreviews_Call) RunAndReturn(run func() (string, error)) *MockChatlogProvider_FetchChatlogPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// FetchConversations provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) FetchConversations() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchConversations")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatlogProvider_FetchConversations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchConversations'
type MockChatlogProvider_FetchConversations_Call struct {
	*mock.Call
}

// FetchConversations is a helper method to define mock.On call
func (_e *MockChatlogProvider_Expecter) FetchConversations() *MockChatlogProvider_FetchConversations_Call {
	return &MockChatlogProvider_FetchConversations_Call{Call: _e.mock.On("FetchConversations")}
}

func (_c *MockChatlogProvider_FetchConversations_Call) Run(run func()) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatlogProvider_FetchConversations_Call) Return(s string, err error) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatlogProvider_FetchConversations_Call) RunAndReturn(run func() (string, error)) *MockChatlogProvider_FetchConversations_Call {
	_c.Call.Return(run)
	return _c
}

// HasEntryInConversation provides a mock function for the type MockChatlogProvider
func (_mock *MockChatlogProvider) HasEntryInConversation(peerAddress string, messageID string) bool {
	ret := _mock.Called(peerAddress, messageID)

	if len(ret) == 0 {
		panic("no return value specified for HasEntryInConversation")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(peerAddress, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockChatlogProvider_HasEntryInConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEntryInConversation'
type MockChatlogProvider_HasEntryInConversation_Call struct {
	*mock.Call
}

// HasEntryInConversation is a helper method to define mock.On call
//   - peerAddress string
//   - messageID string
func (_e *MockChatlogProvider_Expecter) HasEntryInConversation(peerAddress interface{}, messageID interface{}) *MockChatlogProvider_HasEntryInConversation_Call {
	return &MockChatlogProvider_HasEntryInConversation_Call{Call: _e.mock.On("HasEntryInConversation", peerAddress, messageID)}
}

func (_c *MockChatlogProvider_HasEntryInConversation_Call) Run(run func(peerAddress string, messageID string)) *MockChatlogProvider_HasEntryInConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatlogProvider_HasEntryInConversation_Call) Return(b bool) *MockChatlogProvider_HasEntryInConversation_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockChatlogProvider_HasEntryInConversation_Call) RunAndReturn(run func(peerAddress string, messageID string) bool) *MockChatlogProvider_HasEntryInConversation_Call {
	_c.Call.Return(run)
	return _c
}
