// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionDiagnosticProvider creates a new instance of MockConnectionDiagnosticProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionDiagnosticProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionDiagnosticProvider {
	mock := &MockConnectionDiagnosticProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionDiagnosticProvider is an autogenerated mock type for the ConnectionDiagnosticProvider type
type MockConnectionDiagnosticProvider struct {
	mock.Mock
}

type MockConnectionDiagnosticProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionDiagnosticProvider) EXPECT() *MockConnectionDiagnosticProvider_Expecter {
	return &MockConnectionDiagnosticProvider_Expecter{mock: &_m.Mock}
}

// ActiveConnectionsJSON provides a mock function for the type MockConnectionDiagnosticProvider
func (_mock *MockConnectionDiagnosticProvider) ActiveConnectionsJSON() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ActiveConnectionsJSON")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveConnectionsJSON'
type MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call struct {
	*mock.Call
}

// ActiveConnectionsJSON is a helper method to define mock.On call
func (_e *MockConnectionDiagnosticProvider_Expecter) ActiveConnectionsJSON() *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call {
	return &MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call{Call: _e.mock.On("ActiveConnectionsJSON")}
}

func (_c *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call) Run(run func()) *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call) Return(rawMessage json.RawMessage, err error) *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockConnectionDiagnosticProvider_ActiveConnectionsJSON_Call {
	_c.Call.Return(run)
	return _c
}

// ActivePeersJSON provides a mock function for the type MockConnectionDiagnosticProvider
func (_mock *MockConnectionDiagnosticProvider) ActivePeersJSON() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ActivePeersJSON")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionDiagnosticProvider_ActivePeersJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivePeersJSON'
type MockConnectionDiagnosticProvider_ActivePeersJSON_Call struct {
	*mock.Call
}

// ActivePeersJSON is a helper method to define mock.On call
func (_e *MockConnectionDiagnosticProvider_Expecter) ActivePeersJSON() *MockConnectionDiagnosticProvider_ActivePeersJSON_Call {
	return &MockConnectionDiagnosticProvider_ActivePeersJSON_Call{Call: _e.mock.On("ActivePeersJSON")}
}

func (_c *MockConnectionDiagnosticProvider_ActivePeersJSON_Call) Run(run func()) *MockConnectionDiagnosticProvider_ActivePeersJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ActivePeersJSON_Call) Return(rawMessage json.RawMessage, err error) *MockConnectionDiagnosticProvider_ActivePeersJSON_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ActivePeersJSON_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockConnectionDiagnosticProvider_ActivePeersJSON_Call {
	_c.Call.Return(run)
	return _c
}

// ListBannedJSON provides a mock function for the type MockConnectionDiagnosticProvider
func (_mock *MockConnectionDiagnosticProvider) ListBannedJSON() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBannedJSON")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionDiagnosticProvider_ListBannedJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBannedJSON'
type MockConnectionDiagnosticProvider_ListBannedJSON_Call struct {
	*mock.Call
}

// ListBannedJSON is a helper method to define mock.On call
func (_e *MockConnectionDiagnosticProvider_Expecter) ListBannedJSON() *MockConnectionDiagnosticProvider_ListBannedJSON_Call {
	return &MockConnectionDiagnosticProvider_ListBannedJSON_Call{Call: _e.mock.On("ListBannedJSON")}
}

func (_c *MockConnectionDiagnosticProvider_ListBannedJSON_Call) Run(run func()) *MockConnectionDiagnosticProvider_ListBannedJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ListBannedJSON_Call) Return(rawMessage json.RawMessage, err error) *MockConnectionDiagnosticProvider_ListBannedJSON_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ListBannedJSON_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockConnectionDiagnosticProvider_ListBannedJSON_Call {
	_c.Call.Return(run)
	return _c
}

// ListPeersJSON provides a mock function for the type MockConnectionDiagnosticProvider
func (_mock *MockConnectionDiagnosticProvider) ListPeersJSON() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListPeersJSON")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionDiagnosticProvider_ListPeersJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPeersJSON'
type MockConnectionDiagnosticProvider_ListPeersJSON_Call struct {
	*mock.Call
}

// ListPeersJSON is a helper method to define mock.On call
func (_e *MockConnectionDiagnosticProvider_Expecter) ListPeersJSON() *MockConnectionDiagnosticProvider_ListPeersJSON_Call {
	return &MockConnectionDiagnosticProvider_ListPeersJSON_Call{Call: _e.mock.On("ListPeersJSON")}
}

func (_c *MockConnectionDiagnosticProvider_ListPeersJSON_Call) Run(run func()) *MockConnectionDiagnosticProvider_ListPeersJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ListPeersJSON_Call) Return(rawMessage json.RawMessage, err error) *MockConnectionDiagnosticProvider_ListPeersJSON_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockConnectionDiagnosticProvider_ListPeersJSON_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockConnectionDiagnosticProvider_ListPeersJSON_Call {
	_c.Call.Return(run)
	return _c
}
