// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"context"
	"encoding/json"

	"github.com/piratecash/corsa/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatagramProvider creates a new instance of MockDatagramProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatagramProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatagramProvider {
	mock := &MockDatagramProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatagramProvider is an autogenerated mock type for the DatagramProvider type
type MockDatagramProvider struct {
	mock.Mock
}

type MockDatagramProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatagramProvider) EXPECT() *MockDatagramProvider_Expecter {
	return &MockDatagramProvider_Expecter{mock: &_m.Mock}
}

// DatagramReachable provides a mock function for the type MockDatagramProvider
func (_mock *MockDatagramProvider) DatagramReachable(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType) (json.RawMessage, error) {
	ret := _mock.Called(ctx, dst, dtype)

	if len(ret) == 0 {
		panic("no return value specified for DatagramReachable")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PeerIdentity, domain.DType) (json.RawMessage, error)); ok {
		return returnFunc(ctx, dst, dtype)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PeerIdentity, domain.DType) json.RawMessage); ok {
		r0 = returnFunc(ctx, dst, dtype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PeerIdentity, domain.DType) error); ok {
		r1 = returnFunc(ctx, dst, dtype)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatagramProvider_DatagramReachable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatagramReachable'
type MockDatagramProvider_DatagramReachable_Call struct {
	*mock.Call
}

// DatagramReachable is a helper method to define mock.On call
//   - ctx context.Context
//   - dst domain.PeerIdentity
//   - dtype domain.DType
func (_e *MockDatagramProvider_Expecter) DatagramReachable(ctx any, dst any, dtype any) *MockDatagramProvider_DatagramReachable_Call {
	return &MockDatagramProvider_DatagramReachable_Call{Call: _e.mock.On("DatagramReachable", ctx, dst, dtype)}
}

func (_c *MockDatagramProvider_DatagramReachable_Call) Run(run func(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType)) *MockDatagramProvider_DatagramReachable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PeerIdentity
		if args[1] != nil {
			arg1 = args[1].(domain.PeerIdentity)
		}
		var arg2 domain.DType
		if args[2] != nil {
			arg2 = args[2].(domain.DType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatagramProvider_DatagramReachable_Call) Return(rawMessage json.RawMessage, err error) *MockDatagramProvider_DatagramReachable_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockDatagramProvider_DatagramReachable_Call) RunAndReturn(run func(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType) (json.RawMessage, error)) *MockDatagramProvider_DatagramReachable_Call {
	_c.Call.Return(run)
	return _c
}

// ExplainDatagramRoute provides a mock function for the type MockDatagramProvider
func (_mock *MockDatagramProvider) ExplainDatagramRoute(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType, policy domain.RoutePolicy) (json.RawMessage, error) {
	ret := _mock.Called(ctx, dst, dtype, policy)

	if len(ret) == 0 {
		panic("no return value specified for ExplainDatagramRoute")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PeerIdentity, domain.DType, domain.RoutePolicy) (json.RawMessage, error)); ok {
		return returnFunc(ctx, dst, dtype, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PeerIdentity, domain.DType, domain.RoutePolicy) json.RawMessage); ok {
		r0 = returnFunc(ctx, dst, dtype, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PeerIdentity, domain.DType, domain.RoutePolicy) error); ok {
		r1 = returnFunc(ctx, dst, dtype, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatagramProvider_ExplainDatagramRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExplainDatagramRoute'
type MockDatagramProvider_ExplainDatagramRoute_Call struct {
	*mock.Call
}

// ExplainDatagramRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - dst domain.PeerIdentity
//   - dtype domain.DType
//   - policy domain.RoutePolicy
func (_e *MockDatagramProvider_Expecter) ExplainDatagramRoute(ctx any, dst any, dtype any, policy any) *MockDatagramProvider_ExplainDatagramRoute_Call {
	return &MockDatagramProvider_ExplainDatagramRoute_Call{Call: _e.mock.On("ExplainDatagramRoute", ctx, dst, dtype, policy)}
}

func (_c *MockDatagramProvider_ExplainDatagramRoute_Call) Run(run func(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType, policy domain.RoutePolicy)) *MockDatagramProvider_ExplainDatagramRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PeerIdentity
		if args[1] != nil {
			arg1 = args[1].(domain.PeerIdentity)
		}
		var arg2 domain.DType
		if args[2] != nil {
			arg2 = args[2].(domain.DType)
		}
		var arg3 domain.RoutePolicy
		if args[3] != nil {
			arg3 = args[3].(domain.RoutePolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDatagramProvider_ExplainDatagramRoute_Call) Return(rawMessage json.RawMessage, err error) *MockDatagramProvider_ExplainDatagramRoute_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockDatagramProvider_ExplainDatagramRoute_Call) RunAndReturn(run func(ctx context.Context, dst domain.PeerIdentity, dtype domain.DType, policy domain.RoutePolicy) (json.RawMessage, error)) *MockDatagramProvider_ExplainDatagramRoute_Call {
	_c.Call.Return(run)
	return _c
}

// FetchDatagramSummary provides a mock function for the type MockDatagramProvider
func (_mock *MockDatagramProvider) FetchDatagramSummary() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchDatagramSummary")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatagramProvider_FetchDatagramSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDatagramSummary'
type MockDatagramProvider_FetchDatagramSummary_Call struct {
	*mock.Call
}

// FetchDatagramSummary is a helper method to define mock.On call
func (_e *MockDatagramProvider_Expecter) FetchDatagramSummary() *MockDatagramProvider_FetchDatagramSummary_Call {
	return &MockDatagramProvider_FetchDatagramSummary_Call{Call: _e.mock.On("FetchDatagramSummary")}
}

func (_c *MockDatagramProvider_FetchDatagramSummary_Call) Run(run func()) *MockDatagramProvider_FetchDatagramSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatagramProvider_FetchDatagramSummary_Call) Return(rawMessage json.RawMessage, err error) *MockDatagramProvider_FetchDatagramSummary_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockDatagramProvider_FetchDatagramSummary_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockDatagramProvider_FetchDatagramSummary_Call {
	_c.Call.Return(run)
	return _c
}
