// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDiagnosticProvider creates a new instance of MockDiagnosticProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiagnosticProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiagnosticProvider {
	mock := &MockDiagnosticProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDiagnosticProvider is an autogenerated mock type for the DiagnosticProvider type
type MockDiagnosticProvider struct {
	mock.Mock
}

type MockDiagnosticProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiagnosticProvider) EXPECT() *MockDiagnosticProvider_Expecter {
	return &MockDiagnosticProvider_Expecter{mock: &_m.Mock}
}

// DesktopVersion provides a mock function for the type MockDiagnosticProvider
func (_mock *MockDiagnosticProvider) DesktopVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DesktopVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDiagnosticProvider_DesktopVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DesktopVersion'
type MockDiagnosticProvider_DesktopVersion_Call struct {
	*mock.Call
}

// DesktopVersion is a helper method to define mock.On call
func (_e *MockDiagnosticProvider_Expecter) DesktopVersion() *MockDiagnosticProvider_DesktopVersion_Call {
	return &MockDiagnosticProvider_DesktopVersion_Call{Call: _e.mock.On("DesktopVersion")}
}

func (_c *MockDiagnosticProvider_DesktopVersion_Call) Run(run func()) *MockDiagnosticProvider_DesktopVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiagnosticProvider_DesktopVersion_Call) Return(s string) *MockDiagnosticProvider_DesktopVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDiagnosticProvider_DesktopVersion_Call) RunAndReturn(run func() string) *MockDiagnosticProvider_DesktopVersion_Call {
	_c.Call.Return(run)
	return _c
}
