// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"context"

	"github.com/piratecash/corsa/internal/core/domain"
	"github.com/piratecash/corsa/internal/core/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDMRouterProvider creates a new instance of MockDMRouterProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDMRouterProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockDMRouterProvider {
	mock := &MockDMRouterProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDMRouterProvider is an autogenerated mock type for the DMRouterProvider type
type MockDMRouterProvider struct {
	mock.Mock
}

type MockDMRouterProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDMRouterProvider) EXPECT() *MockDMRouterProvider_Expecter {
	return &MockDMRouterProvider_Expecter{mock: &_m.Mock}
}

// SendFileAnnounce provides a mock function for the type MockDMRouterProvider
func (_mock *MockDMRouterProvider) SendFileAnnounce(to domain.PeerIdentity, msg domain.OutgoingDM, meta domain.FileAnnouncePayload, onAsyncFailure func()) error {
	ret := _mock.Called(to, msg, meta, onAsyncFailure)

	if len(ret) == 0 {
		panic("no return value specified for SendFileAnnounce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity, domain.OutgoingDM, domain.FileAnnouncePayload, func()) error); ok {
		r0 = returnFunc(to, msg, meta, onAsyncFailure)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDMRouterProvider_SendFileAnnounce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFileAnnounce'
type MockDMRouterProvider_SendFileAnnounce_Call struct {
	*mock.Call
}

// SendFileAnnounce is a helper method to define mock.On call
//   - to domain.PeerIdentity
//   - msg domain.OutgoingDM
//   - meta domain.FileAnnouncePayload
//   - onAsyncFailure func()
func (_e *MockDMRouterProvider_Expecter) SendFileAnnounce(to interface{}, msg interface{}, meta interface{}, onAsyncFailure interface{}) *MockDMRouterProvider_SendFileAnnounce_Call {
	return &MockDMRouterProvider_SendFileAnnounce_Call{Call: _e.mock.On("SendFileAnnounce", to, msg, meta, onAsyncFailure)}
}

func (_c *MockDMRouterProvider_SendFileAnnounce_Call) Run(run func(to domain.PeerIdentity, msg domain.OutgoingDM, meta domain.FileAnnouncePayload, onAsyncFailure func())) *MockDMRouterProvider_SendFileAnnounce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PeerIdentity
		if args[0] != nil {
			arg0 = args[0].(domain.PeerIdentity)
		}
		var arg1 domain.OutgoingDM
		if args[1] != nil {
			arg1 = args[1].(domain.OutgoingDM)
		}
		var arg2 domain.FileAnnouncePayload
		if args[2] != nil {
			arg2 = args[2].(domain.FileAnnouncePayload)
		}
		var arg3 func()
		if args[3] != nil {
			arg3 = args[3].(func())
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDMRouterProvider_SendFileAnnounce_Call) Return(err error) *MockDMRouterProvider_SendFileAnnounce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDMRouterProvider_SendFileAnnounce_Call) RunAndReturn(run func(to domain.PeerIdentity, msg domain.OutgoingDM, meta domain.FileAnnouncePayload, onAsyncFailure func()) error) *MockDMRouterProvider_SendFileAnnounce_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockDMRouterProvider
func (_mock *MockDMRouterProvider) SendMessage(to domain.PeerIdentity, msg domain.OutgoingDM) {
	_mock.Called(to, msg)
	return
}

// MockDMRouterProvider_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockDMRouterProvider_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - to domain.PeerIdentity
//   - msg domain.OutgoingDM
func (_e *MockDMRouterProvider_Expecter) SendMessage(to interface{}, msg interface{}) *MockDMRouterProvider_SendMessage_Call {
	return &MockDMRouterProvider_SendMessage_Call{Call: _e.mock.On("SendMessage", to, msg)}
}

func (_c *MockDMRouterProvider_SendMessage_Call) Run(run func(to domain.PeerIdentity, msg domain.OutgoingDM)) *MockDMRouterProvider_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PeerIdentity
		if args[0] != nil {
			arg0 = args[0].(domain.PeerIdentity)
		}
		var arg1 domain.OutgoingDM
		if args[1] != nil {
			arg1 = args[1].(domain.OutgoingDM)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDMRouterProvider_SendMessage_Call) Return() *MockDMRouterProvider_SendMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDMRouterProvider_SendMessage_Call) RunAndReturn(run func(to domain.PeerIdentity, msg domain.OutgoingDM)) *MockDMRouterProvider_SendMessage_Call {
	_c.Run(run)
	return _c
}

// SendMessageDelete provides a mock function for the type MockDMRouterProvider
func (_mock *MockDMRouterProvider) SendMessageDelete(ctx context.Context, peer domain.PeerIdentity, target domain.MessageID) error {
	ret := _mock.Called(ctx, peer, target)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PeerIdentity, domain.MessageID) error); ok {
		r0 = returnFunc(ctx, peer, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDMRouterProvider_SendMessageDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageDelete'
type MockDMRouterProvider_SendMessageDelete_Call struct {
	*mock.Call
}

// SendMessageDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - peer domain.PeerIdentity
//   - target domain.MessageID
func (_e *MockDMRouterProvider_Expecter) SendMessageDelete(ctx interface{}, peer interface{}, target interface{}) *MockDMRouterProvider_SendMessageDelete_Call {
	return &MockDMRouterProvider_SendMessageDelete_Call{Call: _e.mock.On("SendMessageDelete", ctx, peer, target)}
}

func (_c *MockDMRouterProvider_SendMessageDelete_Call) Run(run func(ctx context.Context, peer domain.PeerIdentity, target domain.MessageID)) *MockDMRouterProvider_SendMessageDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PeerIdentity
		if args[1] != nil {
			arg1 = args[1].(domain.PeerIdentity)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDMRouterProvider_SendMessageDelete_Call) Return(err error) *MockDMRouterProvider_SendMessageDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDMRouterProvider_SendMessageDelete_Call) RunAndReturn(run func(ctx context.Context, peer domain.PeerIdentity, target domain.MessageID) error) *MockDMRouterProvider_SendMessageDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockDMRouterProvider
func (_mock *MockDMRouterProvider) Snapshot() service.RouterSnapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 service.RouterSnapshot
	if returnFunc, ok := ret.Get(0).(func() service.RouterSnapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(service.RouterSnapshot)
	}
	return r0
}

// MockDMRouterProvider_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockDMRouterProvider_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockDMRouterProvider_Expecter) Snapshot() *MockDMRouterProvider_Snapshot_Call {
	return &MockDMRouterProvider_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockDMRouterProvider_Snapshot_Call) Run(run func()) *MockDMRouterProvider_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDMRouterProvider_Snapshot_Call) Return(routerSnapshot service.RouterSnapshot) *MockDMRouterProvider_Snapshot_Call {
	_c.Call.Return(routerSnapshot)
	return _c
}

func (_c *MockDMRouterProvider_Snapshot_Call) RunAndReturn(run func() service.RouterSnapshot) *MockDMRouterProvider_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}
