// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"github.com/piratecash/corsa/internal/core/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsProvider creates a new instance of MockMetricsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsProvider {
	mock := &MockMetricsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsProvider is an autogenerated mock type for the MetricsProvider type
type MockMetricsProvider struct {
	mock.Mock
}

type MockMetricsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsProvider) EXPECT() *MockMetricsProvider_Expecter {
	return &MockMetricsProvider_Expecter{mock: &_m.Mock}
}

// TrafficSnapshot provides a mock function for the type MockMetricsProvider
func (_mock *MockMetricsProvider) TrafficSnapshot() protocol.Frame {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TrafficSnapshot")
	}

	var r0 protocol.Frame
	if returnFunc, ok := ret.Get(0).(func() protocol.Frame); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(protocol.Frame)
	}
	return r0
}

// MockMetricsProvider_TrafficSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrafficSnapshot'
type MockMetricsProvider_TrafficSnapshot_Call struct {
	*mock.Call
}

// TrafficSnapshot is a helper method to define mock.On call
func (_e *MockMetricsProvider_Expecter) TrafficSnapshot() *MockMetricsProvider_TrafficSnapshot_Call {
	return &MockMetricsProvider_TrafficSnapshot_Call{Call: _e.mock.On("TrafficSnapshot")}
}

func (_c *MockMetricsProvider_TrafficSnapshot_Call) Run(run func()) *MockMetricsProvider_TrafficSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsProvider_TrafficSnapshot_Call) Return(frame protocol.Frame) *MockMetricsProvider_TrafficSnapshot_Call {
	_c.Call.Return(frame)
	return _c
}

func (_c *MockMetricsProvider_TrafficSnapshot_Call) RunAndReturn(run func() protocol.Frame) *MockMetricsProvider_TrafficSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
