// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"encoding/json"

	"github.com/piratecash/corsa/internal/core/domain"
	"github.com/piratecash/corsa/internal/core/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeProvider creates a new instance of MockNodeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockNodeProvider {
	mock := &MockNodeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeProvider is an autogenerated mock type for the NodeProvider type
type MockNodeProvider struct {
	mock.Mock
}

type MockNodeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeProvider) EXPECT() *MockNodeProvider_Expecter {
	return &MockNodeProvider_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockNodeProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) Address() *MockNodeProvider_Address_Call {
	return &MockNodeProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockNodeProvider_Address_Call) Run(run func()) *MockNodeProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_Address_Call) Return(s string) *MockNodeProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeProvider_Address_Call) RunAndReturn(run func() string) *MockNodeProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// CancelFileDownload provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) CancelFileDownload(fileID domain.FileID) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for CancelFileDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.FileID) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeProvider_CancelFileDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelFileDownload'
type MockNodeProvider_CancelFileDownload_Call struct {
	*mock.Call
}

// CancelFileDownload is a helper method to define mock.On call
//   - fileID domain.FileID
func (_e *MockNodeProvider_Expecter) CancelFileDownload(fileID interface{}) *MockNodeProvider_CancelFileDownload_Call {
	return &MockNodeProvider_CancelFileDownload_Call{Call: _e.mock.On("CancelFileDownload", fileID)}
}

func (_c *MockNodeProvider_CancelFileDownload_Call) Run(run func(fileID domain.FileID)) *MockNodeProvider_CancelFileDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FileID
		if args[0] != nil {
			arg0 = args[0].(domain.FileID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_CancelFileDownload_Call) Return(err error) *MockNodeProvider_CancelFileDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeProvider_CancelFileDownload_Call) RunAndReturn(run func(fileID domain.FileID) error) *MockNodeProvider_CancelFileDownload_Call {
	_c.Call.Return(run)
	return _c
}

// ClientVersion provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) ClientVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeProvider_ClientVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientVersion'
type MockNodeProvider_ClientVersion_Call struct {
	*mock.Call
}

// ClientVersion is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) ClientVersion() *MockNodeProvider_ClientVersion_Call {
	return &MockNodeProvider_ClientVersion_Call{Call: _e.mock.On("ClientVersion")}
}

func (_c *MockNodeProvider_ClientVersion_Call) Run(run func()) *MockNodeProvider_ClientVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_ClientVersion_Call) Return(s string) *MockNodeProvider_ClientVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeProvider_ClientVersion_Call) RunAndReturn(run func() string) *MockNodeProvider_ClientVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ExplainFileRoute provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) ExplainFileRoute(dst domain.PeerIdentity) (json.RawMessage, error) {
	ret := _mock.Called(dst)

	if len(ret) == 0 {
		panic("no return value specified for ExplainFileRoute")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) (json.RawMessage, error)); ok {
		return returnFunc(dst)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) json.RawMessage); ok {
		r0 = returnFunc(dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.PeerIdentity) error); ok {
		r1 = returnFunc(dst)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeProvider_ExplainFileRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExplainFileRoute'
type MockNodeProvider_ExplainFileRoute_Call struct {
	*mock.Call
}

// ExplainFileRoute is a helper method to define mock.On call
//   - dst domain.PeerIdentity
func (_e *MockNodeProvider_Expecter) ExplainFileRoute(dst interface{}) *MockNodeProvider_ExplainFileRoute_Call {
	return &MockNodeProvider_ExplainFileRoute_Call{Call: _e.mock.On("ExplainFileRoute", dst)}
}

func (_c *MockNodeProvider_ExplainFileRoute_Call) Run(run func(dst domain.PeerIdentity)) *MockNodeProvider_ExplainFileRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PeerIdentity
		if args[0] != nil {
			arg0 = args[0].(domain.PeerIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_ExplainFileRoute_Call) Return(rawMessage json.RawMessage, err error) *MockNodeProvider_ExplainFileRoute_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockNodeProvider_ExplainFileRoute_Call) RunAndReturn(run func(dst domain.PeerIdentity) (json.RawMessage, error)) *MockNodeProvider_ExplainFileRoute_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllFileTransfers provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) FetchAllFileTransfers() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAllFileTransfers")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeProvider_FetchAllFileTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllFileTransfers'
type MockNodeProvider_FetchAllFileTransfers_Call struct {
	*mock.Call
}

// FetchAllFileTransfers is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) FetchAllFileTransfers() *MockNodeProvider_FetchAllFileTransfers_Call {
	return &MockNodeProvider_FetchAllFileTransfers_Call{Call: _e.mock.On("FetchAllFileTransfers")}
}

func (_c *MockNodeProvider_FetchAllFileTransfers_Call) Run(run func()) *MockNodeProvider_FetchAllFileTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_FetchAllFileTransfers_Call) Return(rawMessage json.RawMessage, err error) *MockNodeProvider_FetchAllFileTransfers_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockNodeProvider_FetchAllFileTransfers_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockNodeProvider_FetchAllFileTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFileMappings provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) FetchFileMappings() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchFileMappings")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeProvider_FetchFileMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFileMappings'
type MockNodeProvider_FetchFileMappings_Call struct {
	*mock.Call
}

// FetchFileMappings is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) FetchFileMappings() *MockNodeProvider_FetchFileMappings_Call {
	return &MockNodeProvider_FetchFileMappings_Call{Call: _e.mock.On("FetchFileMappings")}
}

func (_c *MockNodeProvider_FetchFileMappings_Call) Run(run func()) *MockNodeProvider_FetchFileMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_FetchFileMappings_Call) Return(rawMessage json.RawMessage, err error) *MockNodeProvider_FetchFileMappings_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockNodeProvider_FetchFileMappings_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockNodeProvider_FetchFileMappings_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFileTransfers provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) FetchFileTransfers() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchFileTransfers")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeProvider_FetchFileTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFileTransfers'
type MockNodeProvider_FetchFileTransfers_Call struct {
	*mock.Call
}

// FetchFileTransfers is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) FetchFileTransfers() *MockNodeProvider_FetchFileTransfers_Call {
	return &MockNodeProvider_FetchFileTransfers_Call{Call: _e.mock.On("FetchFileTransfers")}
}

func (_c *MockNodeProvider_FetchFileTransfers_Call) Run(run func()) *MockNodeProvider_FetchFileTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_FetchFileTransfers_Call) Return(rawMessage json.RawMessage, err error) *MockNodeProvider_FetchFileTransfers_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockNodeProvider_FetchFileTransfers_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockNodeProvider_FetchFileTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// HandleLocalFrame provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) HandleLocalFrame(frame protocol.Frame) protocol.Frame {
	ret := _mock.Called(frame)

	if len(ret) == 0 {
		panic("no return value specified for HandleLocalFrame")
	}

	var r0 protocol.Frame
	if returnFunc, ok := ret.Get(0).(func(protocol.Frame) protocol.Frame); ok {
		r0 = returnFunc(frame)
	} else {
		r0 = ret.Get(0).(protocol.Frame)
	}
	return r0
}

// MockNodeProvider_HandleLocalFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLocalFrame'
type MockNodeProvider_HandleLocalFrame_Call struct {
	*mock.Call
}

// HandleLocalFrame is a helper method to define mock.On call
//   - frame protocol.Frame
func (_e *MockNodeProvider_Expecter) HandleLocalFrame(frame interface{}) *MockNodeProvider_HandleLocalFrame_Call {
	return &MockNodeProvider_HandleLocalFrame_Call{Call: _e.mock.On("HandleLocalFrame", frame)}
}

func (_c *MockNodeProvider_HandleLocalFrame_Call) Run(run func(frame protocol.Frame)) *MockNodeProvider_HandleLocalFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 protocol.Frame
		if args[0] != nil {
			arg0 = args[0].(protocol.Frame)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_HandleLocalFrame_Call) Return(frame1 protocol.Frame) *MockNodeProvider_HandleLocalFrame_Call {
	_c.Call.Return(frame1)
	return _c
}

func (_c *MockNodeProvider_HandleLocalFrame_Call) RunAndReturn(run func(frame protocol.Frame) protocol.Frame) *MockNodeProvider_HandleLocalFrame_Call {
	_c.Call.Return(run)
	return _c
}

// NodeStatus provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) NodeStatus() domain.NodeStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeStatus")
	}

	var r0 domain.NodeStatus
	if returnFunc, ok := ret.Get(0).(func() domain.NodeStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.NodeStatus)
	}
	return r0
}

// MockNodeProvider_NodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeStatus'
type MockNodeProvider_NodeStatus_Call struct {
	*mock.Call
}

// NodeStatus is a helper method to define mock.On call
func (_e *MockNodeProvider_Expecter) NodeStatus() *MockNodeProvider_NodeStatus_Call {
	return &MockNodeProvider_NodeStatus_Call{Call: _e.mock.On("NodeStatus")}
}

func (_c *MockNodeProvider_NodeStatus_Call) Run(run func()) *MockNodeProvider_NodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeProvider_NodeStatus_Call) Return(nodeStatus domain.NodeStatus) *MockNodeProvider_NodeStatus_Call {
	_c.Call.Return(nodeStatus)
	return _c
}

func (_c *MockNodeProvider_NodeStatus_Call) RunAndReturn(run func() domain.NodeStatus) *MockNodeProvider_NodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RestartFileDownload provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) RestartFileDownload(fileID domain.FileID) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for RestartFileDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.FileID) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeProvider_RestartFileDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartFileDownload'
type MockNodeProvider_RestartFileDownload_Call struct {
	*mock.Call
}

// RestartFileDownload is a helper method to define mock.On call
//   - fileID domain.FileID
func (_e *MockNodeProvider_Expecter) RestartFileDownload(fileID interface{}) *MockNodeProvider_RestartFileDownload_Call {
	return &MockNodeProvider_RestartFileDownload_Call{Call: _e.mock.On("RestartFileDownload", fileID)}
}

func (_c *MockNodeProvider_RestartFileDownload_Call) Run(run func(fileID domain.FileID)) *MockNodeProvider_RestartFileDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FileID
		if args[0] != nil {
			arg0 = args[0].(domain.FileID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_RestartFileDownload_Call) Return(err error) *MockNodeProvider_RestartFileDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeProvider_RestartFileDownload_Call) RunAndReturn(run func(fileID domain.FileID) error) *MockNodeProvider_RestartFileDownload_Call {
	_c.Call.Return(run)
	return _c
}

// RetryFileChunk provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) RetryFileChunk(fileID domain.FileID) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for RetryFileChunk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.FileID) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeProvider_RetryFileChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryFileChunk'
type MockNodeProvider_RetryFileChunk_Call struct {
	*mock.Call
}

// RetryFileChunk is a helper method to define mock.On call
//   - fileID domain.FileID
func (_e *MockNodeProvider_Expecter) RetryFileChunk(fileID interface{}) *MockNodeProvider_RetryFileChunk_Call {
	return &MockNodeProvider_RetryFileChunk_Call{Call: _e.mock.On("RetryFileChunk", fileID)}
}

func (_c *MockNodeProvider_RetryFileChunk_Call) Run(run func(fileID domain.FileID)) *MockNodeProvider_RetryFileChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FileID
		if args[0] != nil {
			arg0 = args[0].(domain.FileID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_RetryFileChunk_Call) Return(err error) *MockNodeProvider_RetryFileChunk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeProvider_RetryFileChunk_Call) RunAndReturn(run func(fileID domain.FileID) error) *MockNodeProvider_RetryFileChunk_Call {
	_c.Call.Return(run)
	return _c
}

// StartFileDownload provides a mock function for the type MockNodeProvider
func (_mock *MockNodeProvider) StartFileDownload(fileID domain.FileID) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for StartFileDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.FileID) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeProvider_StartFileDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartFileDownload'
type MockNodeProvider_StartFileDownload_Call struct {
	*mock.Call
}

// StartFileDownload is a helper method to define mock.On call
//   - fileID domain.FileID
func (_e *MockNodeProvider_Expecter) StartFileDownload(fileID interface{}) *MockNodeProvider_StartFileDownload_Call {
	return &MockNodeProvider_StartFileDownload_Call{Call: _e.mock.On("StartFileDownload", fileID)}
}

func (_c *MockNodeProvider_StartFileDownload_Call) Run(run func(fileID domain.FileID)) *MockNodeProvider_StartFileDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FileID
		if args[0] != nil {
			arg0 = args[0].(domain.FileID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeProvider_StartFileDownload_Call) Return(err error) *MockNodeProvider_StartFileDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeProvider_StartFileDownload_Call) RunAndReturn(run func(fileID domain.FileID) error) *MockNodeProvider_StartFileDownload_Call {
	_c.Call.Return(run)
	return _c
}
