// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"github.com/piratecash/corsa/internal/core/domain"
	"github.com/piratecash/corsa/internal/core/routing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoutingProvider creates a new instance of MockRoutingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoutingProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoutingProvider {
	mock := &MockRoutingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoutingProvider is an autogenerated mock type for the RoutingProvider type
type MockRoutingProvider struct {
	mock.Mock
}

type MockRoutingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoutingProvider) EXPECT() *MockRoutingProvider_Expecter {
	return &MockRoutingProvider_Expecter{mock: &_m.Mock}
}

// PeerTransport provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) PeerTransport(peerIdentity domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup) {
	ret := _mock.Called(peerIdentity)

	if len(ret) == 0 {
		panic("no return value specified for PeerTransport")
	}

	var r0 domain.PeerAddress
	var r1 domain.NetGroup
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup)); ok {
		return returnFunc(peerIdentity)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) domain.PeerAddress); ok {
		r0 = returnFunc(peerIdentity)
	} else {
		r0 = ret.Get(0).(domain.PeerAddress)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.PeerIdentity) domain.NetGroup); ok {
		r1 = returnFunc(peerIdentity)
	} else {
		r1 = ret.Get(1).(domain.NetGroup)
	}
	return r0, r1
}

// MockRoutingProvider_PeerTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerTransport'
type MockRoutingProvider_PeerTransport_Call struct {
	*mock.Call
}

// PeerTransport is a helper method to define mock.On call
//   - peerIdentity domain.PeerIdentity
func (_e *MockRoutingProvider_Expecter) PeerTransport(peerIdentity interface{}) *MockRoutingProvider_PeerTransport_Call {
	return &MockRoutingProvider_PeerTransport_Call{Call: _e.mock.On("PeerTransport", peerIdentity)}
}

func (_c *MockRoutingProvider_PeerTransport_Call) Run(run func(peerIdentity domain.PeerIdentity)) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PeerIdentity
		if args[0] != nil {
			arg0 = args[0].(domain.PeerIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoutingProvider_PeerTransport_Call) Return(address domain.PeerAddress, network domain.NetGroup) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Return(address, network)
	return _c
}

func (_c *MockRoutingProvider_PeerTransport_Call) RunAndReturn(run func(peerIdentity domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup)) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Return(run)
	return _c
}

// RoutingSnapshot provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) RoutingSnapshot() routing.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RoutingSnapshot")
	}

	var r0 routing.Snapshot
	if returnFunc, ok := ret.Get(0).(func() routing.Snapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(routing.Snapshot)
	}
	return r0
}

// MockRoutingProvider_RoutingSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoutingSnapshot'
type MockRoutingProvider_RoutingSnapshot_Call struct {
	*mock.Call
}

// RoutingSnapshot is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) RoutingSnapshot() *MockRoutingProvider_RoutingSnapshot_Call {
	return &MockRoutingProvider_RoutingSnapshot_Call{Call: _e.mock.On("RoutingSnapshot")}
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) Run(run func()) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) Return(snapshot routing.Snapshot) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) RunAndReturn(run func() routing.Snapshot) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
