// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpc

import (
	"github.com/piratecash/corsa/internal/core/domain"
	"github.com/piratecash/corsa/internal/core/routing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoutingProvider creates a new instance of MockRoutingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoutingProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockRoutingProvider {
	mock := &MockRoutingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoutingProvider is an autogenerated mock type for the RoutingProvider type
type MockRoutingProvider struct {
	mock.Mock
}

type MockRoutingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoutingProvider) EXPECT() *MockRoutingProvider_Expecter {
	return &MockRoutingProvider_Expecter{mock: &_m.Mock}
}

// DigestHeartbeatStats provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) DigestHeartbeatStats() routing.DigestHeartbeatStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DigestHeartbeatStats")
	}

	var r0 routing.DigestHeartbeatStats
	if returnFunc, ok := ret.Get(0).(func() routing.DigestHeartbeatStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(routing.DigestHeartbeatStats)
	}
	return r0
}

// MockRoutingProvider_DigestHeartbeatStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DigestHeartbeatStats'
type MockRoutingProvider_DigestHeartbeatStats_Call struct {
	*mock.Call
}

// DigestHeartbeatStats is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) DigestHeartbeatStats() *MockRoutingProvider_DigestHeartbeatStats_Call {
	return &MockRoutingProvider_DigestHeartbeatStats_Call{Call: _e.mock.On("DigestHeartbeatStats")}
}

func (_c *MockRoutingProvider_DigestHeartbeatStats_Call) Run(run func()) *MockRoutingProvider_DigestHeartbeatStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_DigestHeartbeatStats_Call) Return(digestHeartbeatStats routing.DigestHeartbeatStats) *MockRoutingProvider_DigestHeartbeatStats_Call {
	_c.Call.Return(digestHeartbeatStats)
	return _c
}

func (_c *MockRoutingProvider_DigestHeartbeatStats_Call) RunAndReturn(run func() routing.DigestHeartbeatStats) *MockRoutingProvider_DigestHeartbeatStats_Call {
	_c.Call.Return(run)
	return _c
}

// HealthSnapshot provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) HealthSnapshot() []routing.RouteHealthState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthSnapshot")
	}

	var r0 []routing.RouteHealthState
	if returnFunc, ok := ret.Get(0).(func() []routing.RouteHealthState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RouteHealthState)
		}
	}
	return r0
}

// MockRoutingProvider_HealthSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthSnapshot'
type MockRoutingProvider_HealthSnapshot_Call struct {
	*mock.Call
}

// HealthSnapshot is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) HealthSnapshot() *MockRoutingProvider_HealthSnapshot_Call {
	return &MockRoutingProvider_HealthSnapshot_Call{Call: _e.mock.On("HealthSnapshot")}
}

func (_c *MockRoutingProvider_HealthSnapshot_Call) Run(run func()) *MockRoutingProvider_HealthSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_HealthSnapshot_Call) Return(routeHealthStates []routing.RouteHealthState) *MockRoutingProvider_HealthSnapshot_Call {
	_c.Call.Return(routeHealthStates)
	return _c
}

func (_c *MockRoutingProvider_HealthSnapshot_Call) RunAndReturn(run func() []routing.RouteHealthState) *MockRoutingProvider_HealthSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// JournalCauseStats provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) JournalCauseStats() map[string]uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JournalCauseStats")
	}

	var r0 map[string]uint64
	if returnFunc, ok := ret.Get(0).(func() map[string]uint64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uint64)
		}
	}
	return r0
}

// MockRoutingProvider_JournalCauseStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JournalCauseStats'
type MockRoutingProvider_JournalCauseStats_Call struct {
	*mock.Call
}

// JournalCauseStats is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) JournalCauseStats() *MockRoutingProvider_JournalCauseStats_Call {
	return &MockRoutingProvider_JournalCauseStats_Call{Call: _e.mock.On("JournalCauseStats")}
}

func (_c *MockRoutingProvider_JournalCauseStats_Call) Run(run func()) *MockRoutingProvider_JournalCauseStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_JournalCauseStats_Call) Return(stringToUint64 map[string]uint64) *MockRoutingProvider_JournalCauseStats_Call {
	_c.Call.Return(stringToUint64)
	return _c
}

func (_c *MockRoutingProvider_JournalCauseStats_Call) RunAndReturn(run func() map[string]uint64) *MockRoutingProvider_JournalCauseStats_Call {
	_c.Call.Return(run)
	return _c
}

// OverloadStats provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) OverloadStats() routing.OverloadStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OverloadStats")
	}

	var r0 routing.OverloadStats
	if returnFunc, ok := ret.Get(0).(func() routing.OverloadStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(routing.OverloadStats)
	}
	return r0
}

// MockRoutingProvider_OverloadStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverloadStats'
type MockRoutingProvider_OverloadStats_Call struct {
	*mock.Call
}

// OverloadStats is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) OverloadStats() *MockRoutingProvider_OverloadStats_Call {
	return &MockRoutingProvider_OverloadStats_Call{Call: _e.mock.On("OverloadStats")}
}

func (_c *MockRoutingProvider_OverloadStats_Call) Run(run func()) *MockRoutingProvider_OverloadStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_OverloadStats_Call) Return(overloadStats routing.OverloadStats) *MockRoutingProvider_OverloadStats_Call {
	_c.Call.Return(overloadStats)
	return _c
}

func (_c *MockRoutingProvider_OverloadStats_Call) RunAndReturn(run func() routing.OverloadStats) *MockRoutingProvider_OverloadStats_Call {
	_c.Call.Return(run)
	return _c
}

// PeerTransport provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) PeerTransport(peerIdentity domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup) {
	ret := _mock.Called(peerIdentity)

	if len(ret) == 0 {
		panic("no return value specified for PeerTransport")
	}

	var r0 domain.PeerAddress
	var r1 domain.NetGroup
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup)); ok {
		return returnFunc(peerIdentity)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.PeerIdentity) domain.PeerAddress); ok {
		r0 = returnFunc(peerIdentity)
	} else {
		r0 = ret.Get(0).(domain.PeerAddress)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.PeerIdentity) domain.NetGroup); ok {
		r1 = returnFunc(peerIdentity)
	} else {
		r1 = ret.Get(1).(domain.NetGroup)
	}
	return r0, r1
}

// MockRoutingProvider_PeerTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerTransport'
type MockRoutingProvider_PeerTransport_Call struct {
	*mock.Call
}

// PeerTransport is a helper method to define mock.On call
//   - peerIdentity domain.PeerIdentity
func (_e *MockRoutingProvider_Expecter) PeerTransport(peerIdentity interface{}) *MockRoutingProvider_PeerTransport_Call {
	return &MockRoutingProvider_PeerTransport_Call{Call: _e.mock.On("PeerTransport", peerIdentity)}
}

func (_c *MockRoutingProvider_PeerTransport_Call) Run(run func(peerIdentity domain.PeerIdentity)) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PeerIdentity
		if args[0] != nil {
			arg0 = args[0].(domain.PeerIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoutingProvider_PeerTransport_Call) Return(address domain.PeerAddress, network domain.NetGroup) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Return(address, network)
	return _c
}

func (_c *MockRoutingProvider_PeerTransport_Call) RunAndReturn(run func(peerIdentity domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup)) *MockRoutingProvider_PeerTransport_Call {
	_c.Call.Return(run)
	return _c
}

// ReputationSnapshot provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) ReputationSnapshot() []routing.RouteReputationState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReputationSnapshot")
	}

	var r0 []routing.RouteReputationState
	if returnFunc, ok := ret.Get(0).(func() []routing.RouteReputationState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RouteReputationState)
		}
	}
	return r0
}

// MockRoutingProvider_ReputationSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReputationSnapshot'
type MockRoutingProvider_ReputationSnapshot_Call struct {
	*mock.Call
}

// ReputationSnapshot is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) ReputationSnapshot() *MockRoutingProvider_ReputationSnapshot_Call {
	return &MockRoutingProvider_ReputationSnapshot_Call{Call: _e.mock.On("ReputationSnapshot")}
}

func (_c *MockRoutingProvider_ReputationSnapshot_Call) Run(run func()) *MockRoutingProvider_ReputationSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_ReputationSnapshot_Call) Return(routeReputationStates []routing.RouteReputationState) *MockRoutingProvider_ReputationSnapshot_Call {
	_c.Call.Return(routeReputationStates)
	return _c
}

func (_c *MockRoutingProvider_ReputationSnapshot_Call) RunAndReturn(run func() []routing.RouteReputationState) *MockRoutingProvider_ReputationSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// RoutingSnapshot provides a mock function for the type MockRoutingProvider
func (_mock *MockRoutingProvider) RoutingSnapshot() routing.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RoutingSnapshot")
	}

	var r0 routing.Snapshot
	if returnFunc, ok := ret.Get(0).(func() routing.Snapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(routing.Snapshot)
	}
	return r0
}

// MockRoutingProvider_RoutingSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoutingSnapshot'
type MockRoutingProvider_RoutingSnapshot_Call struct {
	*mock.Call
}

// RoutingSnapshot is a helper method to define mock.On call
func (_e *MockRoutingProvider_Expecter) RoutingSnapshot() *MockRoutingProvider_RoutingSnapshot_Call {
	return &MockRoutingProvider_RoutingSnapshot_Call{Call: _e.mock.On("RoutingSnapshot")}
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) Run(run func()) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) Return(snapshot routing.Snapshot) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockRoutingProvider_RoutingSnapshot_Call) RunAndReturn(run func() routing.Snapshot) *MockRoutingProvider_RoutingSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
