package rpc_test

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/piratecash/corsa/internal/core/domain"
	"github.com/piratecash/corsa/internal/core/routing"
	"github.com/piratecash/corsa/internal/core/rpc"
)

// handler_route_health_test.go covers the Phase 2 PR 11.5
// fetchRouteHealth RPC command. The handler is a pure read over
// the RoutingProvider.HealthSnapshot() data, so the tests use an
// inline RoutingProvider double rather than the autogenerated
// MockRoutingProvider — keeps these tests isolated from the
// mock-regeneration step and makes the contract assertions easier
// to read.

// stubRoutingProvider is a hand-written rpc.RoutingProvider impl
// used only by these tests. The fields are public so test cases
// can mutate them inline (e.g. set health = nil to test empty
// store path).
type stubRoutingProvider struct {
	snapshot   routing.Snapshot
	health     []routing.RouteHealthState
	overload   routing.OverloadStats
	reputation []routing.RouteReputationState
}

func (s *stubRoutingProvider) RoutingSnapshot() routing.Snapshot {
	return s.snapshot
}

func (s *stubRoutingProvider) PeerTransport(_ domain.PeerIdentity) (domain.PeerAddress, domain.NetGroup) {
	return "", ""
}

func (s *stubRoutingProvider) OverloadStats() routing.OverloadStats {
	return s.overload
}

func (s *stubRoutingProvider) HealthSnapshot() []routing.RouteHealthState {
	return s.health
}

// ReputationSnapshot satisfies the Phase 3 PR 12.7 extension of
// the RoutingProvider interface. Tests that exercise
// fetchRouteReputation pre-populate stubRoutingProvider.reputation
// inline; legacy tests leave it nil and the snapshot path
// returns nil unchanged.
func (s *stubRoutingProvider) ReputationSnapshot() []routing.RouteReputationState {
	return s.reputation
}

// TestFetchRouteHealth_UnavailableWhenProviderNil — same "hide
// from help, return 503 on execution" contract as the other
// routing commands have when the provider is nil.
func TestFetchRouteHealth_UnavailableWhenProviderNil(t *testing.T) {
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, nil)

	for _, info := range table.Commands() {
		if info.Name == "fetchRouteHealth" {
			t.Fatal("fetchRouteHealth should be hidden from Commands() when RoutingProvider is nil")
		}
	}
	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.ErrorKind != rpc.ErrUnavailable {
		t.Fatalf("expected ErrUnavailable, got %v", resp.ErrorKind)
	}
}

// TestFetchRouteHealth_EmptyStoreReturnsEmptyStates — when the
// underlying HealthSnapshot is nil (no entries tracked), the
// handler returns an empty states slice and count=0.
func TestFetchRouteHealth_EmptyStoreReturnsEmptyStates(t *testing.T) {
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: time.Now()},
		health:   nil,
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.Error != nil {
		t.Fatalf("expected no error, got %v (kind=%v)", resp.Error, resp.ErrorKind)
	}

	var payload struct {
		States []map[string]interface{} `json:"states"`
		Count  int                      `json:"count"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal body: %v (body=%s)", err, resp.Data)
	}
	if payload.Count != 0 {
		t.Fatalf("count = %d, want 0", payload.Count)
	}
	if len(payload.States) != 0 {
		t.Fatalf("states len = %d, want 0", len(payload.States))
	}
}

// TestFetchRouteHealth_PopulatedSnapshotReturnsAllStates — the
// handler surfaces every tracked state with the documented field
// shape: health string label, rtt_ms milliseconds, RFC3339 timestamps,
// probe_failures counter.
func TestFetchRouteHealth_PopulatedSnapshotReturnsAllStates(t *testing.T) {
	now := time.Date(2026, 5, 23, 12, 0, 0, 0, time.UTC)
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: now},
		health: []routing.RouteHealthState{
			{
				Identity:      "id-target-A",
				Uplink:        "id-uplink-1",
				Health:        routing.HealthGood,
				RTT:           45 * time.Millisecond,
				LastHopAck:    now.Add(-30 * time.Second),
				Confirmed:     true, // PR 11.16: gates last_hop_ack emission on the wire.
				ProbeFailures: 0,
				TransitionAt:  now.Add(-5 * time.Minute),
			},
			{
				Identity:      "id-target-B",
				Uplink:        "id-uplink-2",
				Health:        routing.HealthBad,
				RTT:           250 * time.Millisecond,
				LastHopAck:    now.Add(-150 * time.Second),
				Confirmed:     true, // PR 11.16: stale but historically confirmed.
				LastProbe:     now.Add(-15 * time.Second),
				ProbeFailures: 3,
				TransitionAt:  now.Add(-2 * time.Minute),
			},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.Error != nil {
		t.Fatalf("expected no error, got %v (kind=%v)", resp.Error, resp.ErrorKind)
	}

	var payload struct {
		States []struct {
			Identity      string `json:"identity"`
			Uplink        string `json:"uplink"`
			Health        string `json:"health"`
			RTTMs         int64  `json:"rtt_ms"`
			LastHopAck    string `json:"last_hop_ack"`
			LastProbe     string `json:"last_probe"`
			ProbeFailures int    `json:"probe_failures"`
			TransitionAt  string `json:"transition_at"`
		} `json:"states"`
		Count int `json:"count"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal body: %v (body=%s)", err, resp.Data)
	}
	if payload.Count != 2 {
		t.Fatalf("count = %d, want 2", payload.Count)
	}
	if len(payload.States) != 2 {
		t.Fatalf("states len = %d, want 2", len(payload.States))
	}

	// Sort is by identity asc, uplink asc — target-A first.
	if payload.States[0].Identity != "id-target-A" {
		t.Fatalf("States[0].Identity = %q, want id-target-A", payload.States[0].Identity)
	}
	if payload.States[0].Health != "good" {
		t.Fatalf("States[0].Health = %q, want good", payload.States[0].Health)
	}
	if payload.States[0].RTTMs != 45 {
		t.Fatalf("States[0].RTTMs = %d, want 45", payload.States[0].RTTMs)
	}
	if payload.States[0].ProbeFailures != 0 {
		t.Fatalf("States[0].ProbeFailures = %d, want 0", payload.States[0].ProbeFailures)
	}
	if payload.States[0].LastProbe != "" {
		t.Fatalf("States[0].LastProbe should be empty when zero-time, got %q", payload.States[0].LastProbe)
	}

	if payload.States[1].Identity != "id-target-B" {
		t.Fatalf("States[1].Identity = %q, want id-target-B", payload.States[1].Identity)
	}
	if payload.States[1].Health != "bad" {
		t.Fatalf("States[1].Health = %q, want bad", payload.States[1].Health)
	}
	if payload.States[1].ProbeFailures != 3 {
		t.Fatalf("States[1].ProbeFailures = %d, want 3", payload.States[1].ProbeFailures)
	}
	if payload.States[1].LastProbe == "" {
		t.Fatalf("States[1].LastProbe should be set, got empty")
	}
}

// TestFetchRouteHealth_DeterministicSort — multiple pairs sharing
// the same identity sort by uplink ascending; pairs across
// identities sort by identity ascending. This is the documented
// stable order so test fixtures and operator dashboards stay
// deterministic.
func TestFetchRouteHealth_DeterministicSort(t *testing.T) {
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: time.Now()},
		health: []routing.RouteHealthState{
			{Identity: "id-target-B", Uplink: "id-uplink-2", Health: routing.HealthGood},
			{Identity: "id-target-A", Uplink: "id-uplink-9", Health: routing.HealthGood},
			{Identity: "id-target-A", Uplink: "id-uplink-1", Health: routing.HealthQuestionable},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}

	var payload struct {
		States []struct {
			Identity string `json:"identity"`
			Uplink   string `json:"uplink"`
		} `json:"states"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal body: %v", err)
	}
	if len(payload.States) != 3 {
		t.Fatalf("states len = %d, want 3", len(payload.States))
	}

	want := [][2]string{
		{"id-target-A", "id-uplink-1"},
		{"id-target-A", "id-uplink-9"},
		{"id-target-B", "id-uplink-2"},
	}
	for i, w := range want {
		if payload.States[i].Identity != w[0] || payload.States[i].Uplink != w[1] {
			t.Fatalf("States[%d] = (%q, %q), want (%q, %q)", i, payload.States[i].Identity, payload.States[i].Uplink, w[0], w[1])
		}
	}
}

// TestFetchRouteHealth_HealthLabelsMatchRouteHealth — every
// RouteHealth state's String() label is faithfully reproduced on
// the wire so dashboards can build on stable labels.
func TestFetchRouteHealth_HealthLabelsMatchRouteHealth(t *testing.T) {
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: time.Now()},
		health: []routing.RouteHealthState{
			{Identity: "id-1", Uplink: "u-1", Health: routing.HealthGood},
			{Identity: "id-2", Uplink: "u-1", Health: routing.HealthQuestionable},
			{Identity: "id-3", Uplink: "u-1", Health: routing.HealthBad},
			{Identity: "id-4", Uplink: "u-1", Health: routing.HealthDead},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}
	body := string(resp.Data)
	for _, label := range []string{"good", "questionable", "bad", "dead"} {
		if !strings.Contains(body, `"health":"`+label+`"`) {
			t.Errorf("body missing health label %q: %s", label, body)
		}
	}
}

// TestFetchRouteHealth_DoesNotMutateProviderState — the handler is
// a pure read. After invocation, the provider's HealthSnapshot
// returns the same data (no side effects, no probe triggering).
func TestFetchRouteHealth_DoesNotMutateProviderState(t *testing.T) {
	original := []routing.RouteHealthState{
		{Identity: "id-x", Uplink: "u-1", Health: routing.HealthQuestionable, ProbeFailures: 2},
	}
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: time.Now()},
		health:   original,
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	for i := 0; i < 5; i++ {
		_ = table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	}

	// Provider's underlying state must remain identical — the
	// handler must not call any writer method (no MarkProbeAck,
	// no MarkHopAck, etc.) as a side effect of observation.
	if len(provider.health) != 1 || provider.health[0].ProbeFailures != 2 {
		t.Fatalf("provider state mutated after handler reads: %+v", provider.health)
	}
}

// TestFetchRouteHealth_OmitsLastHopAckWhenNotConfirmed — PR 11.16
// regression. RouteHealthState.LastHopAck is stamped at creation
// (ensureLocked) as the applyIdleTick timer reference and is
// always non-zero for any tracked pair. The wire / RPC contract
// in docs/protocol/route_health.md says last_hop_ack must be
// omitted for pairs that have never been confirmed; the handler
// gates emission on the Confirmed flag.
//
// Two states in the fixture: one Confirmed=true with a real
// LastHopAck (must be emitted), one Confirmed=false with a
// LastHopAck timer-reference stamp (must be omitted on the wire).
func TestFetchRouteHealth_OmitsLastHopAckWhenNotConfirmed(t *testing.T) {
	now := time.Date(2026, 5, 23, 12, 0, 0, 0, time.UTC)
	provider := &stubRoutingProvider{
		snapshot: routing.Snapshot{Routes: map[routing.PeerIdentity][]routing.RouteEntry{}, TakenAt: now},
		health: []routing.RouteHealthState{
			{
				Identity:   "id-confirmed",
				Uplink:     "id-uplink-1",
				Health:     routing.HealthGood,
				LastHopAck: now.Add(-30 * time.Second),
				Confirmed:  true,
			},
			{
				Identity:   "id-unconfirmed",
				Uplink:     "id-uplink-2",
				Health:     routing.HealthQuestionable,
				LastHopAck: now, // timer reference stamped at creation; not a real confirmation.
				Confirmed:  false,
			},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteHealth"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}

	var payload struct {
		States []struct {
			Identity   string `json:"identity"`
			LastHopAck string `json:"last_hop_ack"`
		} `json:"states"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal body: %v (body=%s)", err, resp.Data)
	}
	if len(payload.States) != 2 {
		t.Fatalf("states len = %d, want 2", len(payload.States))
	}

	// Sort is by identity asc: id-confirmed first (c < u).
	if payload.States[0].Identity != "id-confirmed" {
		t.Fatalf("States[0].Identity = %q, want id-confirmed", payload.States[0].Identity)
	}
	if payload.States[0].LastHopAck == "" {
		t.Fatal("Confirmed=true state: last_hop_ack must be emitted, got empty")
	}
	if payload.States[1].Identity != "id-unconfirmed" {
		t.Fatalf("States[1].Identity = %q, want id-unconfirmed", payload.States[1].Identity)
	}
	if payload.States[1].LastHopAck != "" {
		t.Fatalf("Confirmed=false state: last_hop_ack must be OMITTED, got %q (PR 11.15 P3 / 11.16 contract: protocol docs require omitting last_hop_ack for never-confirmed pairs)", payload.States[1].LastHopAck)
	}
}
