package rpc_test

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/piratecash/corsa/internal/core/routing"
	"github.com/piratecash/corsa/internal/core/rpc"
)

// handler_route_reputation_test.go covers Phase 3 PR 12.7
// fetchRouteReputation. The handler shape mirrors
// fetchRouteHealth so the tests follow the same skeleton: stub
// the RoutingProvider inline (avoiding the autogenerated mock
// regeneration step), exercise the unavailable / empty / non-
// empty paths, and pin the sort + omit-empty contract.

// TestFetchRouteReputation_UnavailableWhenProviderNil — the same
// "hidden from help, 503 on execution" contract every routing
// command honours when RoutingProvider is nil.
func TestFetchRouteReputation_UnavailableWhenProviderNil(t *testing.T) {
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, nil)

	for _, info := range table.Commands() {
		if info.Name == "fetchRouteReputation" {
			t.Fatal("fetchRouteReputation should be hidden from Commands() when RoutingProvider is nil")
		}
	}
	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})
	if resp.ErrorKind != rpc.ErrUnavailable {
		t.Fatalf("expected ErrUnavailable, got %v", resp.ErrorKind)
	}
}

// TestFetchRouteReputation_EmptyStoreReturnsEmptyStates — when
// the underlying ReputationSnapshot is nil (no entries tracked)
// the handler returns an empty states slice and count=0.
func TestFetchRouteReputation_EmptyStoreReturnsEmptyStates(t *testing.T) {
	provider := &stubRoutingProvider{}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}
	var payload map[string]interface{}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal: %v (body=%s)", err, resp.Data)
	}
	if count, ok := payload["count"].(float64); !ok || count != 0 {
		t.Fatalf("count = %v, want 0", payload["count"])
	}
	if states, ok := payload["states"].([]interface{}); !ok || len(states) != 0 {
		t.Fatalf("states = %v, want []", payload["states"])
	}
}

// TestFetchRouteReputation_EmitsCounterFields — a populated
// snapshot shows up verbatim in the wire payload. The
// assertion walks the JSON dict to verify every documented
// field is present with the expected value.
func TestFetchRouteReputation_EmitsCounterFields(t *testing.T) {
	cooled := time.Date(2026, 5, 23, 12, 5, 0, 0, time.UTC)
	provider := &stubRoutingProvider{
		reputation: []routing.RouteReputationState{
			{
				Identity:            "id-target",
				Uplink:              "id-uplink",
				HopAckAttempts:      42,
				HopAckSuccesses:     37,
				ReliabilityScore:    0.88,
				ConsecutiveFailures: 1,
				CooldownUntil:       cooled,
			},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}
	var payload struct {
		States []map[string]interface{} `json:"states"`
		Count  int                      `json:"count"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal: %v (body=%s)", err, resp.Data)
	}
	if payload.Count != 1 {
		t.Fatalf("count = %d, want 1", payload.Count)
	}
	state := payload.States[0]
	if state["identity"] != "id-target" {
		t.Fatalf("identity = %v, want id-target", state["identity"])
	}
	if state["uplink"] != "id-uplink" {
		t.Fatalf("uplink = %v, want id-uplink", state["uplink"])
	}
	if got, _ := state["hop_ack_attempts"].(float64); got != 42 {
		t.Fatalf("hop_ack_attempts = %v, want 42", state["hop_ack_attempts"])
	}
	if got, _ := state["hop_ack_successes"].(float64); got != 37 {
		t.Fatalf("hop_ack_successes = %v, want 37", state["hop_ack_successes"])
	}
	if got, _ := state["reliability_score"].(float64); got != 0.88 {
		t.Fatalf("reliability_score = %v, want 0.88", state["reliability_score"])
	}
	if got, _ := state["consecutive_failures"].(float64); got != 1 {
		t.Fatalf("consecutive_failures = %v, want 1", state["consecutive_failures"])
	}
	if got, _ := state["cooldown_until"].(string); got != cooled.Format(time.RFC3339) {
		t.Fatalf("cooldown_until = %v, want %s", state["cooldown_until"], cooled.Format(time.RFC3339))
	}
}

// TestFetchRouteReputation_OmitsCooldownUntilWhenZero — armed-
// cooldown is the optional path; when CooldownUntil is the
// zero time the JSON payload omits the field entirely (rather
// than emitting the misleading "0001-01-01T00:00:00Z" placeholder
// that the JSON encoder would produce by default). Operators
// downstream can rely on "key present" ⇔ "cooldown armed".
func TestFetchRouteReputation_OmitsCooldownUntilWhenZero(t *testing.T) {
	provider := &stubRoutingProvider{
		reputation: []routing.RouteReputationState{
			{
				Identity:        "id-target",
				Uplink:          "id-uplink",
				HopAckAttempts:  5,
				HopAckSuccesses: 5,
			},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}
	if strings.Contains(string(resp.Data), `"cooldown_until":`) {
		t.Fatalf("payload included cooldown_until field for zero-time entry: %s", resp.Data)
	}
}

// TestFetchRouteReputation_SortStableByIdentityThenUplink — the
// handler sorts the wire output ascending by (identity, uplink)
// so RPC consumers see a deterministic ordering. The contract
// matches fetchRouteHealth's sort so a UI joining the two by
// (identity, uplink) can iterate in lockstep.
func TestFetchRouteReputation_SortStableByIdentityThenUplink(t *testing.T) {
	provider := &stubRoutingProvider{
		reputation: []routing.RouteReputationState{
			{Identity: "id-z", Uplink: "id-b"},
			{Identity: "id-a", Uplink: "id-c"},
			{Identity: "id-a", Uplink: "id-b"},
			{Identity: "id-m", Uplink: "id-a"},
		},
	}
	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)

	resp := table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})
	if resp.Error != nil {
		t.Fatalf("unexpected error: %v (kind=%v)", resp.Error, resp.ErrorKind)
	}
	var payload struct {
		States []map[string]interface{} `json:"states"`
	}
	if err := json.Unmarshal(resp.Data, &payload); err != nil {
		t.Fatalf("unmarshal: %v (body=%s)", err, resp.Data)
	}
	want := []struct{ Identity, Uplink string }{
		{"id-a", "id-b"},
		{"id-a", "id-c"},
		{"id-m", "id-a"},
		{"id-z", "id-b"},
	}
	if len(payload.States) != len(want) {
		t.Fatalf("len(states) = %d, want %d", len(payload.States), len(want))
	}
	for i, w := range want {
		gotID, _ := payload.States[i]["identity"].(string)
		gotUp, _ := payload.States[i]["uplink"].(string)
		if gotID != w.Identity || gotUp != w.Uplink {
			t.Fatalf("states[%d] = (%q, %q), want (%q, %q)", i, gotID, gotUp, w.Identity, w.Uplink)
		}
	}
}

// TestFetchRouteReputation_RPCDoesNotMutateProvider — the
// handler is a pure read; calling it must not invoke any
// mutator on the provider. The stub has no mutator methods to
// call, but the test pins the contract by asserting the
// reputation slice is structurally unchanged after Execute.
// Future refactors that accidentally add a side-channel write
// would break this test loud.
func TestFetchRouteReputation_RPCDoesNotMutateProvider(t *testing.T) {
	provider := &stubRoutingProvider{
		reputation: []routing.RouteReputationState{
			{Identity: "id-target", Uplink: "id-uplink", HopAckAttempts: 10},
		},
	}
	before := provider.reputation[0]

	table := rpc.NewCommandTable()
	rpc.RegisterRoutingCommands(table, provider)
	_ = table.Execute(rpc.CommandRequest{Name: "fetchRouteReputation"})

	if provider.reputation[0] != before {
		t.Fatalf("provider mutated: before=%+v, after=%+v", before, provider.reputation[0])
	}
}
