package config

/*
List of fixed seed nodes for the corsa network.
AUTOGENERATED by scripts/generate-seeds.py.

Each line contains a bootstrap peer address in host:port form.
*/
var chainParamSeedsMain = []string{
	"107.191.56.184:64646",
	"135.136.181.48:64646",
	"139.84.176.194:64646",
	"139.84.230.218:64646",
	"65.108.204.190:64646",
	"85.239.51.193:64646",
	"139.84.196.154:64646",
	"216.238.73.170:64646",
}
