// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"github.com/piratecash/corsa/internal/core/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageStore creates a new instance of MockMessageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStore {
	mock := &MockMessageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageStore is an autogenerated mock type for the MessageStore type
type MockMessageStore struct {
	mock.Mock
}

type MockMessageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageStore) EXPECT() *MockMessageStore_Expecter {
	return &MockMessageStore_Expecter{mock: &_m.Mock}
}

// StoreMessage provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) StoreMessage(envelope protocol.Envelope, isOutgoing bool) StoreResult {
	ret := _mock.Called(envelope, isOutgoing)

	if len(ret) == 0 {
		panic("no return value specified for StoreMessage")
	}

	var r0 StoreResult
	if returnFunc, ok := ret.Get(0).(func(protocol.Envelope, bool) StoreResult); ok {
		r0 = returnFunc(envelope, isOutgoing)
	} else {
		r0 = ret.Get(0).(StoreResult)
	}
	return r0
}

// MockMessageStore_StoreMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreMessage'
type MockMessageStore_StoreMessage_Call struct {
	*mock.Call
}

// StoreMessage is a helper method to define mock.On call
//   - envelope protocol.Envelope
//   - isOutgoing bool
func (_e *MockMessageStore_Expecter) StoreMessage(envelope interface{}, isOutgoing interface{}) *MockMessageStore_StoreMessage_Call {
	return &MockMessageStore_StoreMessage_Call{Call: _e.mock.On("StoreMessage", envelope, isOutgoing)}
}

func (_c *MockMessageStore_StoreMessage_Call) Run(run func(envelope protocol.Envelope, isOutgoing bool)) *MockMessageStore_StoreMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 protocol.Envelope
		if args[0] != nil {
			arg0 = args[0].(protocol.Envelope)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageStore_StoreMessage_Call) Return(storeResult StoreResult) *MockMessageStore_StoreMessage_Call {
	_c.Call.Return(storeResult)
	return _c
}

func (_c *MockMessageStore_StoreMessage_Call) RunAndReturn(run func(envelope protocol.Envelope, isOutgoing bool) StoreResult) *MockMessageStore_StoreMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeliveryStatus provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) UpdateDeliveryStatus(receipt protocol.DeliveryReceipt) bool {
	ret := _mock.Called(receipt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeliveryStatus")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(protocol.DeliveryReceipt) bool); ok {
		r0 = returnFunc(receipt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMessageStore_UpdateDeliveryStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeliveryStatus'
type MockMessageStore_UpdateDeliveryStatus_Call struct {
	*mock.Call
}

// UpdateDeliveryStatus is a helper method to define mock.On call
//   - receipt protocol.DeliveryReceipt
func (_e *MockMessageStore_Expecter) UpdateDeliveryStatus(receipt interface{}) *MockMessageStore_UpdateDeliveryStatus_Call {
	return &MockMessageStore_UpdateDeliveryStatus_Call{Call: _e.mock.On("UpdateDeliveryStatus", receipt)}
}

func (_c *MockMessageStore_UpdateDeliveryStatus_Call) Run(run func(receipt protocol.DeliveryReceipt)) *MockMessageStore_UpdateDeliveryStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 protocol.DeliveryReceipt
		if args[0] != nil {
			arg0 = args[0].(protocol.DeliveryReceipt)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_UpdateDeliveryStatus_Call) Return(b bool) *MockMessageStore_UpdateDeliveryStatus_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMessageStore_UpdateDeliveryStatus_Call) RunAndReturn(run func(receipt protocol.DeliveryReceipt) bool) *MockMessageStore_UpdateDeliveryStatus_Call {
	_c.Call.Return(run)
	return _c
}
