// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"github.com/piratecash/corsa/internal/core/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRouter creates a new instance of MockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouter {
	mock := &MockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouter is an autogenerated mock type for the Router type
type MockRouter struct {
	mock.Mock
}

type MockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouter) EXPECT() *MockRouter_Expecter {
	return &MockRouter_Expecter{mock: &_m.Mock}
}

// Route provides a mock function for the type MockRouter
func (_mock *MockRouter) Route(msg protocol.Envelope) RoutingDecision {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 RoutingDecision
	if returnFunc, ok := ret.Get(0).(func(protocol.Envelope) RoutingDecision); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(RoutingDecision)
	}
	return r0
}

// MockRouter_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockRouter_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - msg protocol.Envelope
func (_e *MockRouter_Expecter) Route(msg interface{}) *MockRouter_Route_Call {
	return &MockRouter_Route_Call{Call: _e.mock.On("Route", msg)}
}

func (_c *MockRouter_Route_Call) Run(run func(msg protocol.Envelope)) *MockRouter_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 protocol.Envelope
		if args[0] != nil {
			arg0 = args[0].(protocol.Envelope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_Route_Call) Return(routingDecision RoutingDecision) *MockRouter_Route_Call {
	_c.Call.Return(routingDecision)
	return _c
}

func (_c *MockRouter_Route_Call) RunAndReturn(run func(msg protocol.Envelope) RoutingDecision) *MockRouter_Route_Call {
	_c.Call.Return(run)
	return _c
}
