package overlaysim

// m3a_test.go is the M3-a scenario of
// docs/refactoring/dht/21-anonymity-transport.md §4.3.4″.6: SENSITIVITY TO ROLE
// SKEW — what happens to connectivity, to targets without a Q neighbour (M5) and
// to first-hop refusals (M4) when the share of Q is not one half.
//
// ⚠️ M3-a is not M3-b. This file measures the CONSEQUENCES of a skew that is
// given to it; it says nothing about the skew the real network has. The
// identifiers here are generated by us, so their role split is a property of our
// generator — §4.3.4″.6 says so in as many words, and that is exactly why the
// share is an input rather than a result.
//
// ⚠️ ROLES ARE NEVER ASSIGNED. A requested share is reached by DRAWING
// identifiers from the same generator the model uses and keeping the ones whose
// role — computed by the one classifier, roleOf — is the one still wanted. A
// population built by relabelling nodes would measure a labelling, not the
// classifier's behaviour, and would silently pass if the classifier changed.
//
// ⚠️ Instrument only: no threshold of acceptable skew is proposed here. Which
// skew the mechanism survives is the RESULT of the agreed experiment (point B of
// the queue), and the sweep below is a PROPOSAL awaiting agreement.

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"strings"
)

// population is a set of identifiers with a known role composition, plus every
// parameter needed to draw it again.
type population struct {
	Shape shape
	Seed  uint64
	// ShuffleSeed orders the accepted identifiers.
	//
	// ⚠️ WITHOUT IT THE SKEW WOULD BE MEASURED TOGETHER WITH AN ORDERING. The
	// draw accepts roughly half and half while both halves still have room, and
	// once the minority is full the remainder is pure majority — at a 10 % Q
	// share that is a mixed head and a long ¬Q tail. The model builds the graph
	// in index order, so such a population changes the ORDER nodes are processed
	// in as well as their composition, and the two effects arrive added
	// together. Shuffling the whole population under its own seed separates
	// them.
	ShuffleSeed uint64
	// RequestedShare is the share of Q that was asked for.
	RequestedShare float64
	// Structural and Nodes give the share that was actually obtained. They can
	// differ from the request by at most one node's worth of rounding, and the
	// report prints both rather than the request alone.
	Structural int
	Nodes      int
	// Drawn is how many candidate identifiers were examined to fill the
	// population. It is the cost of the rejection sampling and the evidence
	// that the composition came from selection rather than from assignment.
	Drawn int
	IDs   []nodeID
}

func (p population) ActualShare() float64 {
	if p.Nodes == 0 {
		return 0
	}
	return float64(p.Structural) / float64(p.Nodes)
}

// String records the parameters of the draw. ⚠️ Requested AND actual: a report
// that prints only the request hides the rounding, and one that prints only the
// actual number cannot be reproduced.
func (p population) String() string {
	if p.Nodes == 0 {
		return fmt.Sprintf("population %s, seed %d: empty — no data", p.Shape.name, p.Seed)
	}
	return fmt.Sprintf(
		"population %s (N=%d, d=%d, B=%d), seed %d, shuffle seed %d: Q requested %.3f, "+
			"actual %.3f (%d of %d), %d identifiers drawn",
		p.Shape.name, p.Shape.nodes, p.Shape.degree, p.Shape.budget, p.Seed, p.ShuffleSeed,
		p.RequestedShare, p.ActualShare(), p.Structural, p.Nodes, p.Drawn)
}

// m3aRandom is the reproducible source this scenario orders and samples with. It
// has its own domain separator, so a shuffle can never coincide with an
// identifier, a role or one of the M4 workloads.
func m3aRandom(seed uint64, purpose string, index int) uint64 {
	var buf [16]byte
	binary.LittleEndian.PutUint64(buf[0:8], seed)
	binary.LittleEndian.PutUint64(buf[8:16], uint64(index))
	digest := sha256.Sum256(append([]byte("corsa/overlay/sim/m3a/"+purpose+"/v1"), buf[:]...))
	return binary.LittleEndian.Uint64(digest[:8])
}

// shufflePopulation puts the accepted identifiers into an order that owes
// nothing to how they were accepted — see population.ShuffleSeed for why that is
// not cosmetic. Fisher–Yates, driven by the reproducible source above.
func shufflePopulation(ids []nodeID, shuffleSeed uint64) {
	for i := len(ids) - 1; i > 0; i-- {
		j := int(m3aRandom(shuffleSeed, "shuffle", i) % uint64(i+1))
		ids[i], ids[j] = ids[j], ids[i]
	}
}

// sampleRequesters picks which nodes have their first-hop rule measured.
//
// ⚠️ NOT "the first N". Index order is construction order, and construction
// order decides who ran out of budget first; taking a prefix of it would add a
// second bias on top of the one the shuffle just removed. The sample is drawn
// from the whole population under its own seed, without repetition.
func sampleRequesters(nodes, count int, seed uint64) []int32 {
	if count > nodes {
		count = nodes
	}
	order := make([]int32, nodes)
	for i := range order {
		order[i] = int32(i)
	}
	for i := range count {
		j := i + int(m3aRandom(seed, "requesters", i)%uint64(nodes-i))
		order[i], order[j] = order[j], order[i]
	}
	return order[:count]
}

// drawSkewedPopulation selects identifiers until the requested composition is
// filled, then shuffles them.
//
// Identifiers come from makeNodeID(seed, index) — the model's own generator —
// and are classified by roleOf. A candidate whose half is already full is
// SKIPPED, not relabelled.
//
// ⚠️ THE SHUFFLE IS PART OF THE MEASUREMENT, not tidying. Acceptance order
// correlates with role: while both halves have room the draw takes about half
// and half, and once the minority is full everything that follows is majority.
// At a 10 % Q share that is a mixed head and a long ¬Q tail — and since the
// model builds in index order, such a population would change WHO IS PROCESSED
// FIRST as well as the composition. Two effects arriving added together cannot
// be told apart afterwards, so the order is randomised under a separate seed
// that the report records.
func drawSkewedPopulation(sh shape, seed, shuffleSeed uint64, requestedShare float64) (population, error) {
	if requestedShare < 0 || requestedShare > 1 {
		return population{}, fmt.Errorf("requested Q share %.3f is outside 0…1", requestedShare)
	}

	wantStructural := int(float64(sh.nodes)*requestedShare + 0.5)
	wantOther := sh.nodes - wantStructural

	ids := make([]nodeID, 0, sh.nodes)
	structural, other, drawn := 0, 0, 0

	// A cap, so an impossible request fails with an explanation instead of
	// spinning: both halves are about half the identifier space, so filling
	// either takes about 2N draws and this is a wide margin.
	limit := 64*sh.nodes + 1024
	for len(ids) < sh.nodes {
		if drawn >= limit {
			return population{}, fmt.Errorf(
				"could not fill %s at Q share %.3f after %d draws: got %d Q and %d ¬Q",
				sh.name, requestedShare, drawn, structural, other)
		}
		candidate := makeNodeID(seed, drawn)
		drawn++

		if roleOf(candidate) == roleStructural {
			if structural >= wantStructural {
				continue
			}
			structural++
		} else {
			if other >= wantOther {
				continue
			}
			other++
		}
		ids = append(ids, candidate)
	}

	shufflePopulation(ids, shuffleSeed)

	return population{
		Shape:          sh,
		Seed:           seed,
		ShuffleSeed:    shuffleSeed,
		RequestedShare: requestedShare,
		Structural:     structural,
		Nodes:          len(ids),
		Drawn:          drawn,
		IDs:            ids,
	}, nil
}

// --- the guard model ---------------------------------------------------------

// guardModel says HOW a guard set is built for the M4 part of the scenario, and
// what is assumed rather than simulated.
//
// ⚠️ THIS IS A PROPOSAL, NOT AN ADOPTED MODEL. The M1 stand builds
// neighbourhoods; it has no guard sets, no liveness, no transit capability and
// no identity proofs. Every one of those has to come from somewhere, and here
// they come from declarations — which is why they are named in the report next
// to every number they produced.
type guardModel struct {
	// SetSize is how many members a pinned set holds — the code's sampled set
	// is min(maxSampledGuards = 12, a share of the neighbourhood), so the
	// proposal keeps it small and explicit rather than modelling roomLocked.
	SetSize int
	// ConfirmedPrefix is how many of them are treated as confirmed.
	ConfirmedPrefix int
	// Requests is how many targets each measured requester puts to the rule.
	Requests int
	// TargetSeed makes the uniform workload reproducible.
	TargetSeed uint64
}

// Assumptions is printed with every M4 number this scenario produces.
func (m guardModel) Assumptions() string {
	return fmt.Sprintf(
		"guard model (PROPOSAL, not adopted): set = the first %d ¬Q neighbours in the built graph, "+
			"first %d of them treated as confirmed, %d uniform targets per requester, seed %d. "+
			"⚠️ ASSUMED, NOT SIMULATED: alive, transit-capable and identity-proven are declared "+
			"true for every member — the model simulates none of the three, so a refusal rate "+
			"measured here is a LOWER BOUND. Only ¬Q comes from the graph",
		m.SetSize, m.ConfirmedPrefix, m.Requests, m.TargetSeed)
}

// buildGuardSet forms the pinned set of one requester from the GRAPH: its ¬Q
// neighbours, in adjacency order.
//
// ⚠️ The neighbours are real — that part is simulated. The flags are not: see
// guardModel.Assumptions. Returning the count of ¬Q neighbours found separately
// from the requested size is what makes "not enough suitable guards" a measured
// fact rather than an invisible truncation.
func buildGuardSet(g *graph, requester int32, model guardModel) guardSet {
	set := guardSet{
		Name:    fmt.Sprintf("node %d, first %d ¬Q neighbours", requester, model.SetSize),
		Members: make([]guardMember, 0, model.SetSize),
	}
	for _, neighbour := range g.adjacency[requester] {
		if len(set.Members) >= model.SetSize {
			break
		}
		if g.roles[neighbour] == roleStructural {
			continue
		}
		set.Members = append(set.Members, guardMember{
			Node:           neighbour,
			Alive:          true,
			TransitCapable: true,
			IdentityProven: true,
			Confirmed:      len(set.Members) < model.ConfirmedPrefix,
		})
	}
	return set
}

// --- one run -----------------------------------------------------------------

// skewWorkload says what the measured requesters aim at. Recorded in the report:
// a refusal rate means nothing without it.
type skewWorkload int

const (
	// skewUniformTargets — targets drawn uniformly over the network. The
	// neutral load: the guard set is a handful of nodes, so the rule rarely
	// bites and what the skew does to first hops shows up on its own.
	skewUniformTargets skewWorkload = iota
	// skewTargetsTheConfirmedGuard — every request of a requester aims at the
	// CONFIRMED member of its own set. The degenerate probe of §4.3.4″.3
	// applied per requester: it is the load under which the confirmed-only and
	// the whole-set readings of the rule are forced apart, which is what makes
	// the open sub-question measurable at all.
	skewTargetsTheConfirmedGuard
)

func (w skewWorkload) String() string {
	if w == skewUniformTargets {
		return "uniform targets"
	}
	return "every request aims at the requester's confirmed guard"
}

// skewSetup is one point of the sweep. It is a struct rather than eight
// positional arguments because every field is a parameter of the published
// number and has to be recorded with it.
type skewSetup struct {
	Shape          shape
	Seed           uint64
	ShuffleSeed    uint64
	RequestedShare float64
	Quota          int
	Policy         policy
	Guards         guardModel
	Workload       skewWorkload
	// Requesters is how many nodes have their first-hop rule measured, and
	// RequesterSeed picks WHICH ones — independently of construction order.
	Requesters    int
	RequesterSeed uint64
}

// m3aRun is one measured point: a population, the policy it was built under, and
// the measurements taken on it.
type m3aRun struct {
	Setup      skewSetup
	Population population

	// Connectivity of the induced Q-subgraph — the M1 criterion, re-measured
	// here because it is what the skew is expected to move first.
	Connectivity componentReport
	// Neighbourless is M5 over the same graph.
	Neighbourless m5Report

	// RefusalsConfirmed and RefusalsSampled are M4 under the TWO readings
	// §4.3.4″.3 leaves open, over THE SAME requests.
	//
	// ⚠️ Both are kept. An earlier version aggregated only the sampled
	// population, and the effect of ConfirmedPrefix — the whole reason the
	// sub-question exists — disappeared from the results while a comment
	// claimed it was reported per set. A measurement that quietly picks one
	// side of an open decision has answered it.
	RefusalsConfirmed m4Slice
	RefusalsSampled   m4Slice

	// RequestersMeasured is the M4 denominator in requesters, and
	// RequestersShortOfGuards how many of them could not fill the set size the
	// guard model asked for — an undersized set is a finding, not a detail.
	RequestersMeasured      int
	RequestersShortOfGuards int
}

// describeConnectivity renders the subgraph report. ⚠️ An EMPTY subgraph is
// "no data", never "one component": at a Q share of zero there is nothing to be
// connected, and a criterion that reads that as a pass would accept the one
// population in which the structural plane cannot exist at all.
func describeConnectivity(report componentReport) string {
	if report.Nodes == 0 {
		return "no data"
	}
	return fmt.Sprintf("%d nodes, %d components, largest %.4f, isolated %d",
		report.Nodes, report.Components, report.LargestShare(), report.Isolated)
}

func (r m3aRun) String() string {
	guardLine := "no data"
	if r.RequestersMeasured > 0 {
		guardLine = fmt.Sprintf(
			"%d requesters sampled with seed %d (independently of construction order), "+
				"%d short of the requested set size",
			r.RequestersMeasured, r.Setup.RequesterSeed, r.RequestersShortOfGuards)
	}
	return fmt.Sprintf(
		"%s\npolicy %s, quota %d, load: %s\n  Q-subgraph:  %s\n  M5 all:      %s\n"+
			"  M5 Q:        %s\n  M5 ¬Q:       %s\n  M4 confirmed only: %s\n"+
			"  M4 whole set:      %s\n  M4 inputs:   %s\n  %s",
		r.Population, r.Setup.Policy, r.Setup.Quota, r.Setup.Workload,
		describeConnectivity(r.Connectivity),
		r.Neighbourless.All, r.Neighbourless.Structural, r.Neighbourless.NonStructural,
		r.RefusalsConfirmed, r.RefusalsSampled, guardLine, r.Setup.Guards.Assumptions())
}

// runSkewPoint builds one population and measures it.
//
// Setup.Requesters limits how many nodes have their first-hop rule measured: M4
// over every node of a large population buys nothing, since the refusal rate is
// an average over requesters either way. WHICH ones is drawn under its own seed
// — see sampleRequesters.
func runSkewPoint(setup skewSetup) (m3aRun, error) {
	sh := setup.Shape
	people, err := drawSkewedPopulation(sh, setup.Seed, setup.ShuffleSeed, setup.RequestedShare)
	if err != nil {
		return m3aRun{}, err
	}

	g := buildGraphOnIDs(people.IDs, sh, setup.Quota, setup.Policy, nil, nil)

	// The classification must survive the whole path from draw to built graph.
	for i := range g.roles {
		if g.roles[i] != roleOf(g.ids[i]) {
			return m3aRun{}, fmt.Errorf("node %d carries role %d, the classifier says %d",
				i, g.roles[i], roleOf(g.ids[i]))
		}
	}

	neighbourless, err := measureNeighbourlessTargets(g)
	if err != nil {
		return m3aRun{}, err
	}

	run := m3aRun{
		Setup:         setup,
		Population:    people,
		Connectivity:  analyseComponents(g, func(i int32) bool { return g.roles[i] == roleStructural }),
		Neighbourless: neighbourless,
	}

	model := setup.Guards
	uniform := uniformWorkload(model.TargetSeed, sh.nodes, model.Requests)

	for _, requester := range sampleRequesters(sh.nodes, setup.Requesters, setup.RequesterSeed) {
		set := buildGuardSet(g, requester, model)
		if len(set.Members) < model.SetSize {
			run.RequestersShortOfGuards++
		}

		load := uniform
		if setup.Workload == skewTargetsTheConfirmedGuard {
			load = confirmedGuardWorkload(set, model.Requests)
		}

		report, err := measureFirstHopRefusals(g, set, load)
		if err != nil {
			return m3aRun{}, err
		}
		// ⚠️ BOTH readings, over the SAME requests: `report` measured one
		// workload twice, once per population, so the two aggregates below
		// differ only by the rule they apply — not by what they were asked.
		addRefusals(&run.RefusalsConfirmed, report.Confirmed)
		addRefusals(&run.RefusalsSampled, report.Sampled)
		run.RequestersMeasured++
	}
	return run, nil
}

// addRefusals accumulates one requester's result into an aggregate.
func addRefusals(total *m4Slice, one m4Slice) {
	total.Requests += one.Requests
	total.Served += one.Served
	total.RefusedNobodySuitable += one.RefusedNobodySuitable
	total.RefusedByTargetExclusion += one.RefusedByTargetExclusion
}

// confirmedGuardWorkload aims every request at the requester's confirmed guard.
//
// ⚠️ With no confirmed member there is nothing to aim at, so the load falls back
// to the first member, and to node 0 for an empty set: either way the request
// refuses for its own reason and the fallback cannot manufacture a difference
// between the two populations.
func confirmedGuardWorkload(set guardSet, requests int) workload {
	target := int32(0)
	reason := "the set is empty, so requests aim at node 0"
	for _, member := range set.Members {
		if member.Confirmed {
			target, reason = member.Node, "the confirmed member of the set"
			break
		}
	}
	if reason == "the set is empty, so requests aim at node 0" && len(set.Members) > 0 {
		target = set.Members[0].Node
		reason = "no member is confirmed, so requests aim at the first one"
	}

	load := mainContactInSetWorkload(target, requests)
	load.Name = "targets the confirmed guard"
	load.Parameters = fmt.Sprintf("every request targets node %d — %s", target, reason)
	return load
}

// --- the sweep, as a proposal -------------------------------------------------

// m3aProposal is the sweep this scenario SUGGESTS running once the candidate and
// the guard model are agreed. ⚠️ It is not run by any test here and none of its
// numbers is an adopted parameter: the range, the step and the guard model are
// the things to agree ON, not conclusions from them.
type m3aProposal struct {
	Shapes    []shape
	Seeds     []uint64
	FromShare float64
	ToShare   float64
	Step      float64
	Quota     int
	Policy    policy
	Guards    guardModel
	// Requesters is how many nodes per point have their refusals measured, and
	// the two seeds decide the population's ORDER and WHICH nodes are measured
	// — both kept apart from the identifier seed so that a skew does not arrive
	// mixed with an ordering.
	Requesters    int
	ShuffleSeed   uint64
	RequesterSeed uint64
	// Workloads are run at every point: the neutral one, and the one that forces
	// the confirmed and the whole-set readings apart.
	Workloads []skewWorkload
}

// proposedSkewSweep is the concrete suggestion, written down so it can be
// argued with. Every number in it is a proposal.
func proposedSkewSweep() m3aProposal {
	return m3aProposal{
		Shapes:    []shape{{name: "10k×8", nodes: 10_000, degree: 8, budget: 16}},
		Seeds:     []uint64{1, 2, 3, 4, 5},
		FromShare: 0.05,
		ToShare:   0.95,
		Step:      0.05,
		Quota:     1,
		Policy:    policyInitiatedLimit,
		Guards: guardModel{
			SetSize:         3,
			ConfirmedPrefix: 1,
			Requests:        200,
			TargetSeed:      7,
		},
		Requesters:    200,
		ShuffleSeed:   101,
		RequesterSeed: 202,
		Workloads:     []skewWorkload{skewUniformTargets, skewTargetsTheConfirmedGuard},
	}
}

// Points lists the shares the proposal would visit.
func (p m3aProposal) Points() []float64 {
	shares := make([]float64, 0, 32)
	for share := p.FromShare; share <= p.ToShare+1e-9; share += p.Step {
		shares = append(shares, share)
	}
	return shares
}

func (p m3aProposal) String() string {
	names := make([]string, 0, len(p.Shapes))
	for _, sh := range p.Shapes {
		names = append(names, sh.name)
	}
	loads := make([]string, 0, len(p.Workloads))
	for _, load := range p.Workloads {
		loads = append(loads, load.String())
	}
	return fmt.Sprintf(
		"PROPOSED skew sweep — AWAITING AGREEMENT, not an adopted parameter set:\n"+
			"  shapes %s, seeds %v\n"+
			"  Q share from %.2f to %.2f step %.2f (%d points)\n"+
			"  policy %s, quota %d, %d requesters per point\n"+
			"  order seed %d, requester seed %d — separate from the identifier seed so a skew "+
			"is not measured together with an ordering\n"+
			"  loads: %s\n"+
			"  %s\n"+
			"  ⚠️ Open decisions: the guard model above; whether the confirmed-only or the whole "+
			"sampled population is normative (§4.3.4″.3); the acceptable skew itself, which is the "+
			"RESULT of this experiment and not an input to it",
		strings.Join(names, ", "), p.Seeds, p.FromShare, p.ToShare, p.Step, len(p.Points()),
		p.Policy, p.Quota, p.Requesters, p.ShuffleSeed, p.RequesterSeed,
		strings.Join(loads, "; "), p.Guards.Assumptions())
}
